- upload/serializers.py
- upload/tests/test_serializers.py
- upload/views/uploads.py
didn't like how we were sending the destination url. Using the serializer instead
> Send destination url the proper way

- services/task/task.py
- upload/tests/views/test_upload_completion.py
- upload/urls.py
- upload/views/upload_completion.py
Create a new endpoint that marks the completion step for uploads. This endpoint should trigger a task that has all the logic for marking uploads as complete. The task hasn't been implemented yet, so I'll leave it as a TODO for now. will add it once it's implemented
> upload completion endpoint - manual notifs trigger

- utils/config.py
- utils/tests/unit/test_config.py
After moving `ReportDetails.files_array` and `Commit.report` to archive successfilly for Codecov
we want to do the same for some selected customers (in `repo_ids`) and then we will want
to start the process for new fields. Only for codecov.
The way things were before, if you have a field set to write to GCS it is valid for all codecov
repos AND all repos under `repo_ids`, while we would only want that for codecov repos.
So by changing the `master_write_switch` to strings we can have more power over each individual
field. Now we can use:
*  `True` or `codecov_access` to write *only* for codecov repos
*  `restricted_access` to write to all repos in `repo_ids` (+ codecov)
*  `general_access` to write to all repos
Because currently we're only writing for codecov repos the change will not …
> chore: change logic to write data to storage

- codecov_auth/management/commands/set_trial_status_values.py
- codecov_auth/management/commands/tests/test_set_trial_status_values.py
This script is to set the initial trial_status values for customers before launching trials. This PR adds some cases that weren't considered in the 1st pass 
- Adds edge case for free + invoiced customers
- Adds tests
> Add edge cases to consider free + invoiced customers

- README.md
replaces "open source" in top disclaimer of readme
Edits Readme
> Replace "open source" in README

- codecov_auth/admin.py
- codecov_auth/helpers.py
- codecov_auth/middleware.py
- codecov_auth/tests/unit/test_helpers.py
https://github.com/codecov/platform-team/issues/116
- Create helper function to log to admin log entry
- Log to admin log in impersonation middleware
- Add `__str__` method to User
> Add impersonation to django admin log

- services/report.py
- services/tests/test_report.py
Resolves https://codecov.sentry.io/issues/4399295225/?project=5215654&referrer=assigned_activity-email
A self-reminder that sometimes it's worth writing tests even for the simple looking edge cases
> fix: Fix reference to commit's repo id

- core/models.py
- reports/models.py
- utils/model_utils.py
- utils/tests/unit/test_model_utils.py
Don't share default values. The present changes make it so we always
generate a new reference to a new object when returning the default value, rather than
the same pointer to all objects using `ArchiveField`.
In terms of logging reducing the level of the line that says both dbfield and
archive_field are None. It was spamming the logs …
> fix: dont share default_values + log fix

- upload/helpers.py
- upload/tests/test_upload.py
- upload/views/legacy.py
This is being done to gather metrics on the source of an upload and its version.
https://github.com/codecov/platform-team/issues/120
- Add regex to package schema in query params schema
- Increment metric based on source of upload in upload legacy endpoint
> Metrics based on source of upload in legacy endpoint

- api/internal/owner/serializers.py
- api/internal/tests/views/test_account_viewset.py
Adjust phases for scheduled changes to take the last phase 
Adjust serializer + test
> Fixed scheduled phases where there's more than 1 scheduled phase

- utils/migrations.py
Out of convenience in order to be used in migrations instead of `RiskyRunSQL` to run risky `AlterField` operations
- Create `RiskyAlterField` class in `utils.migrations` that wraps the `AlterField` migration class with "Risky"
> Add RiskyAlterField to utils/migrations

- graphql_api/tests/test_commit.py
- graphql_api/types/upload/upload.py
Adjust the download_url surfaced to the client.
- Adjusts download_url + test related to it
> Adjust donwload_url link

- codecov_auth/commands/owner/interactors/get_uploads_number_per_user.py
- Fix indentation for monthly_upload_limit
- Retract ReadOnlyReport on comparison as we're getting errors from our public api
> bug: Fix indentation for monthly_upload_limit and misc

- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
Removes restriction that `OrgLevelToken` is cloud-exclusive.
closes codecov/codecov-api#123 …
> fix: Make OrgLevelToken work for self-hosted

- core/management/commands/backfill_commits.py
- core/tests/test_management_commands.py
- services/task/task.py
- services/tests/test_task.py
I had thought `commitid` was the SHA but it is not.
> fix: Backfill task takes commit ID instead of sha

- graphql_api/tests/test_pull.py
- graphql_api/types/comparison/comparison.graphql
- graphql_api/types/comparison/comparison.py
- graphql_api/types/pull/pull.py
- services/comparison.py
instead of fetching the missing base commit error and check for first pull, we fetch the new type and handle in gazebo.
https://github.com/codecov/engineering-team/issues/535
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm …
> feat: Update comparison result with first pull request type

- services/task/task.py
- upload/tests/views/test_reports.py
- upload/views/reports.py
trigger pre-process task for codecov only repos 
> trigger preprocess upload for codecov repos only

- api/public/v2/report/views.py
- codecov_auth/tests/unit/views/test_bitbucket.py
- codecov_auth/tests/unit/views/test_bitbucket_server.py
- codecov_auth/views/bitbucket.py
- codecov_auth/views/bitbucket_server.py
- conftest.py
- services/path.py
- services/tests/test_path.py
Addresses multiple vulnerabilities detected by GH code scanning alerts.
https://github.com/codecov/internal-issues/issues/53
https://github.com/codecov/internal-issues/issues/54
https://github.com/codecov/internal-issues/issues/55
https://github.com/codecov/internal-issues/issues/70
https://github.com/codecov/internal-issues/issues/71
Fixes https://github.com/codecov/codecov-api/security/code-scanning/5
Fixes https://github.com/codecov/codecov-api/security/code-scanning/6
Fixes https://github.com/codecov/codecov-api/security/code-scanning/7
These tickets boil down to 2 vulnerabilities described below. 
* Encrypts the OAuth token data before saving it in a cookie
- for BitBucket and BitBucket server
- also signs the cookie for good measure
* Addresses a potential DoS on a path regex that …
> fix: Address various security scanning vulerabilities

- services/task/task.py
The API should be able to enqueue a task to send an email to a user.
Fixes: https://github.com/codecov/engineering-team/issues/158
- Creates a helper function to dispatch a send email task to the worker
entry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.
> Add send email task to task service

- codecov_auth/tests/unit/views/test_base.py
- codecov_auth/views/base.py
We don't want to save the student status of an owner if it's false
Fixes: https://github.com/codecov/engineering-team/issues/644
- Only save student status from user_dict to owner if user_dict student status is True
> don't save student status to owner if it is false

- upload/tests/views/test_reports.py
- upload/views/reports.py
> triggering pre-process upload for all users

- services/analytics.py
- services/tests/test_analytics.py
shared is expecting "user_id" to be part of the owner object traits, and the traits had owner_id instead that's why it was sending -1 
> segment is expecting user_id not owner_id, fixing it

- services/analytics.py
- services/tests/test_analytics.py
We want to send to segment the org_id as user_id for upload events 
> sending org id for upload events

- codecov/commands/base.py
- codecov/commands/exceptions.py
- codecov/commands/tests/test_base.py
- codecov_auth/commands/owner/interactors/save_terms_agreement.py
- codecov_auth/commands/owner/interactors/tests/test_get_is_current_user_an_admin.py
- graphql_api/actions/owner.py
- graphql_api/helpers/mutation.py
- graphql_api/tests/test_owner.py
- graphql_api/urls.py
To be able to use TOS with service less requests, we need to update the mutation (graphql endpoints) to accept no service, and raise a proper exception otherwise. 
- Add new MissingService exception 
- Allow non-service based TOS mutation 
- Add tests 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in …
> ref: Accept service less requests gq

- labelanalysis/serializers.py
The count for label analysis only fires after validation.
So that is the total number of _valid_ label analysis requests.
The actual total number of requets that we receive need to be fired
_before_ the payload validation.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and …
> chore: fix label-analysis metrics placement

- upload/helpers.py
This query was quite slow at times.  See here for p99 response time > 60s in some cases: https://codecov.sentry.io/performance/summary/spans/db:500d772238719a7c/?environment=production&project=5215654&query=http.method%3APOST&statsPeriod=7d&transaction=%2Fupload%2F%7Bversion%7D%2F
Presumably there's just lots of contention for that repo row and updates are waiting on locks.  The actual query itself is conditional on the primary key so it's not like adding an index would speed that up or anything.
Depends on https://github.com/codecov/worker/pull/150
* Removes the update to `repos.updatestamp` (this will now happen in the worker - see here: https://github.com/codecov/worker/pull/150)
* only update the `active/activated/deleted` state if it actually changed
> Only auto-activate if state has changed, remove update to repo.updatestamp

- codecov/commands/base.py
- codecov/commands/executor.py
- codecov/commands/tests/test_executor.py
- codecov_auth/commands/owner/interactors/save_terms_agreement.py
- codecov_auth/commands/owner/interactors/tests/test_save_terms_agreement.py
passing current_user to use instead of relying on owner
TBD
- Handled current user in executor 
- Default to none user, so we don't go over 1000 tests :D 
- Refactor save terms interactor to handle user specific fields  
..
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and …
> ref: Handle current_user in base

- upload/views/reports.py
We were triggering the pre-process upload task for our internal use. Now we're rolling it out for all users 
> trigger pre-process upload for all users now

- services/report.py
Speed up filtering by flags in GraphQL endpoints by rewriting the search function to be able to compute faster on average.
Change it to exit each of the nested for loops quicker by not going through the entire iterator.
https://github.com/codecov/engineering-team/issues/691 …
> fix: speedup flag filtering in GraphQL API

- graphql_api/actions/repository.py
- graphql_api/tests/test_current_user_ariadne.py
- graphql_api/types/inputs/repository_set_filters.graphql
- On GraphQL `viewableRepository` resolver, add ability to filter repo list by public/private.
- If `isPublic` is not provided it will return both public and private repos
- If `isPublic=true` it will only return public repos
- If `isPublic=false` it will only return private repos
https://github.com/codecov/engineering-team/issues/724
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm …
> feat: add a filter for public/private repo filter for viewableRepository

- webhook_handlers/views/github.py
A cross-site scripting vulnerability was detected, this PR attempts to remove that vulnerability
Fixes: https://github.com/codecov/internal-issues/issues/68
Remove ref_type value from Response in github webhook handler
> Fix XSS vulnerability by removing ref_type from Response

- codecov_auth/tests/unit/views/test_github.py
- codecov_auth/views/github.py
Resolves https://github.com/codecov/internal-issues/issues/126
If we don't receive an `access_token` during the GitHub OAuth flow then we can't really continue with the login since we'll be missing basically all the info about them.  I still don't entirely understand what exactly triggers this condition so I'm logging everything else we get back from GitHub in this case.
> fix: Skip login if GitHub OAuth does not return access_token

- graphs/badges/badges.py
- graphs/tests/test_badge_handler.py
- graphs/tests/test_helpers.py
- graphs/views.py
Moves the small badge mask over to leave space for 100% while still looking good with 2 digits. Hopefully this addresses examples like https://community.codecov.com/t/badge-width-is-incorrect-when-cov-is-100-and-precision-is-not-zero/2600/2
https://github.com/orgs/codecov/projects/31/views/11?pane=issue&itemId=34798619
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate …
> Update small badge

- requirements.txt
Fixes Django security vulnerabilities by updating to the fix version:
- Django Denial-of-service in django.utils.text.Truncator
- Django potential denial of service vulnerability in UsernameField on Windows
- Django Denial of service vulnerability in django.utils.encoding.uri_to_iri
https://github.com/codecov/internal-issues/issues/140
https://github.com/codecov/internal-issues/issues/139
https://github.com/codecov/internal-issues/issues/135
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain …
> fix: Upgrade Django version to fix security vulnerabilities

- requirements.in
- requirements.txt
The versions of `urllib3` and `opentelemetry-instrumentation` we currently use have vulnerabilities, we can fix them by updating.
Fixes: https://github.com/codecov/internal-issues/issues/104
- Put restriction on urllib3 to be above version `1.26.17`
- Put restriction on opentelemetry-instrumentation-django to be above version `0.41b0`
- Put restriction on opentelemetry-sdk to be above `1.20.0`
> Fix urllib and opentelemetry-instrumentation dependencies

- dev.sh
- enterprise.sh
- prod.sh
- staging.sh
minor update to reduce some prod errors in the logs
> fix(launchscripts): delete contents of prometheus multiproc dir, not dir itself

- codecov/settings_base.py
- utils/logging_configuration.py
This is for https://github.com/codecov/infrastructure-team/issues/162 -- it enables GUnicorn access logs to be output as JSON instead of as HTTP access log format.
> feat(logging): change access logging format to JSON

- .github/workflows/ci.yml
> Use the same sentry version

- plan/constants.py
Adjust benefits to better reflect what the plan does 
> feat: adjust benefits for team plan

- graphql_api/tests/test_branch.py
- requirements.in
- requirements.txt
- services/path.py
https://github.com/codecov/shared/pull/83
https://github.com/codecov/internal-issues/issues/155
sentry traces show `ReportPaths.single_directory()` taking a while in the `BranchContents` graphql query handler. it basically returns a flat list of directory/file objects with the names/totals of each. it calls `report.get(path).totals` to get the totals which does more processing than is strictly necessary.
https://github.com/codecov/shared/pull/83 adds a new `get_file_totals()` method to `Report`/`ReadOnlyReport` that returns the values from the `ReportFileSummary`
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me …
> perf: use new get_file_totals() report method for BranchContents

- upload/helpers.py
- upload/tests/test_helpers.py
Should resolve https://codecov.sentry.io/issues/4643278430
If we fail to fetch an access token using the GitHub app installation then just fallback to trying to find an acceptable OAuth token for the bot token.
> fix: Fallback to OAuth bot token when installation token fails

- graphql_api/tests/test_components.py
- graphql_api/types/comparison/comparison.graphql
- graphql_api/types/comparison/comparison.py
- graphql_api/types/inputs/components_filters.graphql
we need this to filter components tab **and** to filter components on search term 
https://github.com/codecov/engineering-team/issues/838
- Update comparison to handle the filter
- Tests 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
> feat: Support filters in componentComparisons

- api/public/v2/report/views.py
- graphql_api/tests/test_branch.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
- graphql_api/types/component/component.py
- graphql_api/types/inputs/path_contents_filters.graphql
- services/components.py
- services/tests/test_components.py
Adds component filtering in pathContents query
https://github.com/codecov/engineering-team/issues/825
> feat: Support components filter in pathContents (#825)

- codecov_auth/admin.py
Creates a linkable field in owner view on admin page that goes to the user view, if the owner has a user associated.
https://github.com/codecov/engineering-team/issues/837
> feat: add user link to owner view on admin page (#837)

- codecov_auth/models.py
https://sentry.slack.com/archives/C04MGV3DF8D/p1701451737952949?thread_ts=1701451230.594479&cid=C04MGV3DF8D …
> Allow Sentry email aliases to be made staff users

- upload/serializers.py
- upload/tests/views/test_reports.py
- upload/views/base.py
- upload/views/reports.py
Follow up from https://github.com/codecov/codecov-api/pull/287
N/A
Starts populating the `report_type` column when we create new commit reports or query for existing commit reports (as part of upload).
> feat: Start populating report_type column

- api/public/v2/report/views.py
- api/public/v2/tests/test_report_viewset.py
Fix the regex pattern matching for path filtering for Reports. `*` pattern will consume the previous pattern 0 or more times, in this case `{path}.*` means prefix matching. Before, `{path}*` will unintentionally consume the previous character of the path string.
https://github.com/codecov/internal-issues/issues/148 …
> fix: Report filtering by path pattern string (#internal_148)

- codecov_auth/tests/unit/views/test_logout.py
- codecov_auth/views/logout.py
- change logout_view redirect url to hardcoded dashboard url in settings
> fix: update logout_view to redirect to dashboard_url

- codecov/views.py
> Our number 1 query by volume is our own health check endpoint
* Cache the result of the version query for the lifetime of the process.
* Perform a check on the db connection state so that the health endpoint returns 500 when the db is down.
> Reduce db queries coming from health endpoint

- api/shared/permissions.py
- core/commands/flag/interactors/delete_flag.py
See https://github.com/codecov/feedback/issues/181
- Allow erase repository coverage
- Allow flag deletion
> fix: allow self hosted admins to have parity with cloud admins

- codecov_auth/tests/unit/views/test_base.py
- codecov_auth/tests/unit/views/test_github.py
- codecov_auth/tests/unit/views/test_github_enterprise.py
- codecov_auth/tests/unit/views/test_gitlab.py
- codecov_auth/views/base.py
- codecov_auth/views/github.py
- codecov_auth/views/gitlab.py
Sometimes when a user tries to install the github app (on self-hosted), they will encounter a 400 response
Fixes: https://github.com/codecov/engineering-team/issues/806
- change return of `get_redirection_url_from_state` to tuple
- if second element of tuple is False, it means that the state was not set and we should redirect to the dashboard without logging the user in
> fix: stop returning 400 code when user installs github app

- codecov_auth/models.py
- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.graphql
- graphql_api/types/owner/owner.py
We're adding a resolver to surface whether a repo has any private repos.
https://github.com/codecov/engineering-team/issues/939
- Adds a resolver for an owner to surface if it has any private repos
- Adds a property to the owner model …
> feat: add resolver to expose private repos

- webhook_handlers/tests/test_github.py
- webhook_handlers/tests/test_github_enterprise.py
- webhook_handlers/views/github.py
Closes https://github.com/codecov/internal-issues/issues/150
Adds a quick extra params to ghm customers
> feat: expand message for gm marketplace customer when customer has previous plan

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Following up from #321, adds the language field to the Repository type. This will be consumed in gazebo to conditionally render an `ATS` tab. This PR closes https://github.com/codecov/engineering-team/issues/930. 
https://github.com/codecov/engineering-team/issues/930 …
> [feat] Add primary language field to repository GQL

- services/billing.py
- services/tests/test_billing.py
Customers want to update the stripe email address via Gazebo. This is the backend portion for this change.
- Add `update_email_address` fn and tests
> feat: add fn to update stripe email address

- Makefile
- codecov/settings_dev.py
- docker/Dockerfile-proxy
- docker/frpc-entrypoint.sh
- docker/frpc.ini
We occasionally test Stripe locally, and to do so we need to expose our local setup to the world. We normally use Ngrok, but we have an inhouse solution, this ticket, instead to save us some money.
- Add frpc proxy setup information + minutiae to ensure the new setup works
> 957 add frp proxy

- webhook_handlers/tests/test_github.py
- webhook_handlers/tests/test_github_enterprise.py
- webhook_handlers/views/github.py
Following up from https://github.com/codecov/internal-issues/issues/150, add some extra fields to our logs if the user has an active subscription. More info about the payload object [here](https://docs.github.com/en/apps/github-marketplace/using-the-github-marketplace-api-in-your-app/webhook-events-for-the-github-marketplace-api). 
Adding the following info to logs:
- From plan
- From no. seats
- To plan
- To no. seats
This closes https://github.com/codecov/internal-issues/issues/151
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …
> Improve logging for GHM plan changes

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
- upload/views/bundle_analysis.py
For client app to know whether use has bundle analysis enabled:
- When a upload endpoint is called for a bundle analysis type, set the flag to true in DB.
- Allow GQL to query this field
https://github.com/codecov/engineering-team/issues/1005 …
> feat: Update and retrieve bundle_analysis_enabled field

- core/tests/factories.py
- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Add a resolver for `Repository` to return list of languages for the given repo.
https://github.com/codecov/engineering-team/issues/963
> feat: Add fetching of repo languages in GQL

- requirements.in
- requirements.txt
Updating shared to use the latest user schema validation for `flag_list_structure`
> update shared version

- upload/views/bundle_analysis.py
Allow clients to send null values for the params that are not required. Null values are appropriately handled by the API.
https://github.com/codecov/engineering-team/issues/1052
> feat: allow nulls in non-required params for BA upload endpoint

- graphql_api/tests/test_config.py
- graphql_api/types/config/config.graphql
- graphql_api/types/config/config.py
Show all git providers that Codecov supports
https://github.com/codecov/engineering-team/issues/947
> feat: GQL expose list of all git providers

- graphql_api/tests/test_pull_comparison.py
- graphql_api/types/comparison/comparison.graphql
- graphql_api/types/comparison/comparison.py
- graphql_api/types/inputs/flag_comparison_filters.graphql
Related to https://github.com/codecov/engineering-team/issues/823, this PR updates the flags comparison type to accept a filter that allows lookups by flag term. This is required in the front end to allow the search field in the flags selector to apply to the query. 
This closes https://github.com/codecov/engineering-team/issues/1064. 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> [feat] Allow search by term for flag comparisons

- api/internal/coverage/views.py
- api/public/v2/branch/serializers.py
- api/shared/mixins.py
- graphql_api/types/branch/branch.py
- graphs/tests/test_badge_handler.py
- graphs/views.py
- utils/temp_branch_fix.py
This commit is a fix for the recent issue where
branch heads were all set to the same value each
time they were updated due to a bug in the Branch
django model.
This fix creates a helper function that checks for the 2 remaining innacurate commit shas that a large number of branches were set to. If the current branch head is set to one of those shas, we update the branch head by fetching the latest commit on that branch from the db.
Note that we must use a raw sql query here to update the branch object because using the django ORM to update it would lead to the same issue we are trying to fix.
https://status.codecov.com/incidents/z10fykg3c9w4
- create `get_or_update_branch_head`
- use `get_or_update_branch_head` function in many endpoints most notably: graphs (badges) and the graphql …
> fix: fetch accurate branch head

- services/repo_providers.py
- services/tests/test_repo_providers.py
- upload/helpers.py
- upload/tests/test_helpers.py
- utils/github.py
- webhook_handlers/tests/test_github.py
- webhook_handlers/tests/test_github_enterprise.py
- webhook_handlers/views/github.py
This reverts commit 86178ba3e3a4f1f57cd0e957c25d5979766376b6.
This commit caused auth issues with `/graphql` endpoint in which users were not authenticated and couldn't see source code.
Revertign for now while we figure out the exact issue and fix it.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in …
> Revert "feat: use GithubAppInstallation in api (#347)"

- utils/temp_branch_fix.py
`timestamp` is the field which we were using before to decide if a commit was to be branch's head or not. The issue with ordering by `updatestamp` is that `updatestamp` is nullable which leads to incorrect behaviour where we may pick a commit from very long ago to be the branch head. 
- order by timestamp descending instead of updatestamp descending
> fix: use timestamp of commit instead of updatestamp in get_or_update_branch_head

- codecov/settings_staging.py
https://github.com/codecov/infrastructure-team/issues/174
> feat(gazebo-previews): update CORS header for API to allow our self-hosted previews

- api/internal/tests/views/test_coverage_viewset.py
- api/public/v2/tests/test_report_viewset.py
- api/public/v2/tests/test_totals_viewset.py
- graphql_api/types/branch/branch.py
- graphs/tests/test_badge_handler.py
- utils/temp_branch_fix.py
We want to apply this fix to all branches, not just branches that have the name `master` or `main`
- removed the check for the commit sha in the temp branch fix
- add a check to exit the function early if the branch head matches the latest commit
> fix: apply temp branch fix to all branches

- codecov_auth/admin.py
We are adding back the uses_invoice checkbox in the admin
- Adds the uses_invoice field back to the serializer
- Creates the checkbox input for the uses invoice field
> feat: add back uses invoice checkbox

- api/internal/owner/serializers.py
- api/internal/tests/views/test_account_viewset.py
Forgot to add this when making the API ticket to change the billing email from the client
> feat: add email to the stripe customer serializer

- api/public/v2/branch/serializers.py
using `refresh_from_db` on a branch object causes a similar issue as trying to update a branch object and saving using the django orm due to the primary key of the django model only being part of the actual composite primary key of the postgres table
[Relevant ticket](https://codecov.sentry.io/discover/api:9e20c3ff8fa54786822981e267c7530e/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=5215654&query=http.url%3Ahttp%3A%2F%2Fapi.codecov.io%2Fapi%2Fv2%2Fgithub%2Fcodecov%2Frepos%2Fcodecov-demo%2Fbranches%2Fmain%2F+event.type%3Aerror&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29)
- remove call to `branch.refresh_from_db`
- replace by using value of branch head returned by `get_or_update_branch_head`
> fix: remove branch.refresh_from_db from branch serializer

- upload/tests/views/test_empty_upload.py
- upload/views/empty_upload.py
Users may want to bypass the files check of the empty upload endpoint and force a passing notification
https://github.com/codecov/engineering-team/issues/1015
CLI change: https://github.com/codecov/codecov-cli/pull/362
Accepts a should_force boolean field in the data for this endpoint, if it's true then we send a passing notification else we do the regular behaviour of this endpoint
> feat: support force flag in empty upload endpoint:

- codecov/settings_base.py
> Making upload throttle toggleable

- graphql_api/dataloader/bundle_analysis.py
- graphql_api/dataloader/tests/test_bundle_analysis.py
- graphql_api/tests/test_commit.py
Handle the case when commit report is created, but can't load report for some reason (eg upload failed)
https://github.com/codecov/engineering-team/issues/1139
> fix: handle no uploads check

- upload/serializers.py
- upload/tests/test_serializers.py
We noticed that we query the flags from an upload inside the loop
and decided to move that to the outside to reduce hits to the database
> fix: optimize n+1 query when creating upload

- api/internal/tests/views/test_account_viewset.py
- graphql_api/tests/test_owner.py
- plan/service.py
- plan/test_plan.py
We want to roll out the team plan to all orgs that has less than 11 activated users.  
https://github.com/codecov/engineering-team/issues/1122
- Remove trial conditions to serve this plan to basic and free users 
- Fix tests 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, …
> fix: Update available plan to remove trial condition

- utils/rollouts.py
We're adding more users to the test results feature rollout
> chore: add more users to test results rollout

- codecov_auth/commands/owner/interactors/tests/test_trigger_sync.py
- codecov_auth/commands/owner/interactors/trigger_sync.py
- services/refresh.py
- services/task/task.py
Use the `manual_trigger` option when clicking the sync repos button in the UI, this will get propagated to sync languages task to reach out to GH for languages.
https://github.com/codecov/engineering-team/issues/961
> add manual trigger option when clicking sync repos

- codecov/settings_base.py
- core/middleware.py
- core/tests/test_middleware.py
This change adds the User-Agent http header to our prometheus metrics that we expose so that we can have a better understanding of where traffic comes from for our API. We can visualize the data via Grafana by the different User-Agents and it could give us insights in how our users use the codecov cli, uploader, etc.. 
- subclass the provided django_prometheus middlewares, but add the additional label when appropriate
- add unit tests to ensure functionality
You can view the exposed metrics at http://localhost:8000/monitoring/metrics, but I wasn't able to try querying in Grafana. Do we need to deploy to staging to test that? 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired …
> feat: add user agent to prom metrics

- requirements.in
- requirements.txt
- upload/helpers.py
- upload/tests/views/test_uploads.py
- upload/views/legacy.py
- upload/views/test_results.py
- upload/views/uploads.py
Adding Sentry DDM to the various upload endpoints
Fixes: https://github.com/codecov/engineering-team/issues/1178
- `generate_upload_sentry_metrics_tags` in upload helpers to generate tags for metrics, tags are:
- agent: uploader or cli
- version: which version of the agent
- action: coverage vs test results
- private: is the repo the upload is being made to private?
- is_shelter_request: is the request coming from shelter
- `get_agent_from_headers` and `get_version_from_headers` to parse `User-Agent` header to get agent and version, if it fails to parse it will return `unsupported-user-agent`
Note: My auto formatter went off while saving some of the files and the linter did not undo them, so this PR comes with some formatting changes to some of the files that have not been visited …
> feat: measure uploads using sentry metrics

- upload/views/bundle_analysis.py
Don't drop the `branch` param in the validator because we actually need it
> fix: Don't drop branch arg from BA upload endpoint

- upload/views/legacy.py
We want a percentage of orgs using the CLI vs using the uploader.
This sentry metrics set was previously added to the new upload endpoint.
- Add sentry_metrics.set call to the legacy upload endpoint
> feat: add sentry metrics set to legacy endpoint

- .gitignore
- Makefile
- codecov/settings_test.py
- dev.sh
Figured out how to get the built-in `Debug` feature to work on my local IDE, required these few tweaks.
Full setup steps are in Notion.
- `api` container can accept commands after startup
- `make build` creates a required file that was missing
- adds to `.gitignore`
> Chore: updates for local development

- codecov/admin.py
- codecov/forms.py
- codecov/settings_base.py
- codecov/urls.py
- codecov/views.py
- core/middleware.py
- requirements.in
- requirements.txt
https://github.com/codecov/codecov-api/assets/159859649/dfdb68ec-1f94-4221-be74-290045e51928
Adds the new feature models from [here](https://github.com/codecov/shared/pull/130) to django admin so that we can assign feature variants to features dynamically
> feat: hookup feature models to django admin

- plan/service.py
- plan/test_plan.py
- utils/tests/unit/test_coverage_measurements.py
- utils/uploads_used.py
We're adding a partitioned with the UserMeasurements models. We want to add some functions to add/query for monthly uploads. This PR adds those + tests
https://github.com/codecov/engineering-team/issues/1174
- adds a query + insert functions using the user measurements model
- adds tests to those
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry …
> feat: add methods to query + insert coverage measurements

- services/profiling.py
- upload/views/empty_upload.py
Aim of this PR is to fail a little bit faster when doing the regex matching.
.NET's native timeout value for regex matching looks to be 2 seconds.
- Lowers timeout value from 5 seconds to 2
> fix: Use Smaller timeout value when regex matching

- codecov/tests/test_views.py
- codecov/views.py
Adds more natural querying to django admin for feature flags overrides. Should also speed up the query since no longer using `icontains`. Closes points 5 & 6 from here: https://github.com/codecov/engineering-team/issues/1315
https://github.com/codecov/codecov-api/assets/159859649/e448ee47-9047-4b10-ab8b-080fa0ad584e …
> feat: improve querying capabilities

- upload/serializers.py
Fixes: https://github.com/codecov/engineering-team/issues/1297
- Add a ci_service field to the `UploadSerializer` that is `write_only`
> Add ci_service field to upload endpoint

- graphql_api/helpers/mutation.py
- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.py
Currently a GQL error will appear for Unauthenticated/Unauthorized requests, this change makes it so that those fields would return null instead. Making this change because the UI calls for unauthorized fields would not spam Sentry errors. …
> GQL Owners: return null for unauthorized fields

- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
We want to handle receiving a 429 or 403
status code response from gh that is related
to hitting the gh rate limit.
now we do that when we try to get PR info while
trying to auth with tokenless
we will return a `exceptions.Throttled` which
corresponds to a 429 status code
https://github.com/codecov/engineering-team/issues/1247
- Handle `TorngitRateLimitError` in `get_pull_request_info`
- add tests for `get_pull_request_info` to test it can handle receiving a 429 status code
> fix: handle rate limit error in get pr info fn

- codecov_auth/tests/test_admin.py
- plan/service.py
Currently the admin app can extend a org trial, but only after they have expired and turned back to basic plan.
This change allows the orgs' trials to be extended while they're still trialing.
> [admin] allow trial extension for orgs currently on trial

- upload/serializers.py
- upload/tests/test_serializers.py
there is a possibility of creating commits concurrently if that happens there is a possibility of getting an IntegrityError when trying to create the Commit object
this commit solves this problem by using get_or_create to create the Commit object in the serializer
- remove repository and commitid from validated data so its not included in the defaults
- use `get_or_create` instead of `filter` then `super().create`
> fix: use get_or_create in CommitSerializer.create

- graphql_api/tests/test_commit.py
- graphql_api/tests/test_pull.py
- graphql_api/types/bundle_analysis/base.graphql
- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/bundle_analysis/comparison.graphql
- graphql_api/types/bundle_analysis/comparison.py
- graphql_api/types/bundle_analysis/report.graphql
- graphql_api/types/bundle_analysis/report.py
This reverts commit 7932e93a02c2fb7f916992c59798c2ff2635ca8e.
Gazebo is actually still using these.
> Revert "Bundle Analysis: delete old code (#444)"

- graphql_api/tests/test_components.py
- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Adds the ComponentMeasurementsBackfilled boolean to the repository model similar to the flagsMeasurementsBackfilled key, with similar UT's as well.
closes https://github.com/codecov/engineering-team/issues/1359
Adds a new key to the repository model, and resolver + tests
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, …
> feat: #1359 - Add Component Measurements Backfilled resolver + tests

- graphql_api/tests/test_components.py
- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Part of larger Component epic: https://github.com/codecov/engineering-team/issues/234
Closes: https://github.com/codecov/engineering-team/issues/1368
Adds the component count resolver + related tests to the Repository graphQL model
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
> feat: Add Component Count Resolver to Repository GQL model

- utils/tests/unit/test_coverage_measurements.py
Not sure why moving the freeze below fixed it, perhaps something with the call below it?
One other thing, updated datetime.utcnow -> datetime.now(timezone.utc) since its deprecated
- Saw failures on https://github.com/codecov/codecov-api/actions/runs/8382528674/job/22985958375?pr=465 and was able to reproduce on main
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact …
> fix: flakey coverage measurement test

- codecov_auth/models.py
- codecov_auth/tests/unit/test_models.py
- webhook_handlers/tests/test_github.py
- webhook_handlers/views/github.py
The configuration for ghapps need to be done carefully before they can
be used. And that process is _manual_.
However it's very simple for a user to simply go and install an app to
their organization and point it's webhooks to us. In this case we would
think it's the default app and break the app.
So now we update the app's names everytime we get a new webhook for it.
Only the configured default app may use the default name, all others,
unless they manually receive a custom name, will be 'unconfigured_app'.
Closes: https://github.com/codecov/engineering-team/issues/1445
Look, I get it. …
> fix: carefully assign ghapp names

- api/public/v2/repo/views.py
Update openAPI type from string to array for better clarity on the docs here: https://docs.codecov.com/reference/repos_list
closes https://github.com/codecov/feedback/issues/284
- updates repo_list endpoint's names property on the OpenAPI schema from string to array
- this should hopefully allow us to test names='A'&names='B' on the schema tester
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by …
> fix: Update OpenAPI type to Array from string

- dev.sh
- enterprise.sh
> [ezpz]: fix: uppercase enterprise env var name

- codecov_auth/models.py
- codecov_auth/tests/unit/test_models.py
Recently an enterprise customer had a ghapp instance of the default
app change names to `unconfigured_app` even though it is the default
app.
One possible explanation is that in the YAML the default app id is a string,
not a number. This small change is to catch that case.
The motivation is:
```
>>> 10 == 10
True
>>> 10 == '10'
False
>>> str(10) == str('10')
True
```
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights …
> make `is_configured` more rebust

- graphql_api/tests/test_components.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
> rename from componentMeasurements to components

- codecov_auth/models.py
- codecov_auth/tests/unit/test_models.py
- webhook_handlers/views/github.py
We had again a situation in staging that the default app flipped names to 'unconfigured_app'.
Not sure why exactly, but it's anoying and disruptive.
These changes emit a warning when the app flips name to unconfigured so we can track better
that situation (but we hope it doesn't happen much) and hopefully get better understanding
on why it's happening.
I also made a change to the `is_configured` function that an app unconfigured is never configured.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In …
> Warn when ghapps flip names

- codecov/settings_base.py
Add ability to configure cors extra headers. Also adds a default with the "baggage" header that is used by the sentry sdk.
> Add ability to configure cors extra headers

- graphql_api/tests/test_repository.py
- graphql_api/types/component/component.graphql
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Add a new GQL field in Repository to get all components in the YAML, returning the `id` and `name`, allow searching by a term
> add getting components from yaml GQL

- graphql_api/tests/test_components.py
- graphql_api/types/component/component.graphql
- services/components.py
Add a last uploaded timestamp to components measurement for the last measurement data point for this measurement ID.
> components over time add lastUploaded

- services/path.py
If BranchContents has flag filtering need to build the FilteredReportFiles to get the accurate coverage totals instead of using the current minimal way of processing.
https://github.com/codecov/internal-issues/issues/370
> fix: flag filtering for branch contents

- Makefile
- dev.sh
- docker/Dockerfile
- docker/Dockerfile-proxy
- docker/Dockerfile.requirements
- enterprise.sh
- prod.sh
- staging.sh
fixes https://github.com/codecov/engineering-team/issues/1242
with an alpine/musl image we have to build more packages from source. grpcio takes an eternity to build for example
also apparently alpine/musl images have DNS resolution problems
this uses an official "slim" python image based on debian stable. from a quick glance at uncompressed image sizes on my local machine, this is actually 300mb smaller:
i have not rigorously tested this but it seems okay
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest …
> chore: use debian base images instead of alpine

- Makefile
Uploading test results in CI is not working
Updates version of the Codecov CLI in the CI to a version that supports uploading test results.
> build: update the CLI version to upload test results

- services/components.py
> fix: last uploaded for components over time

- api/public/v2/component/serializers.py
- api/public/v2/component/views.py
- api/public/v2/tests/test_api_component_viewset.py
Title. User suggestion, seems like a nice to have feature!
Closes https://github.com/codecov/feedback/issues/150
> Return component coverage percentage in public components list api

- graphql_api/actions/components.py
- graphql_api/actions/measurements.py
- graphql_api/tests/test_components.py
- graphql_api/types/repository/repository.py
- services/components.py
Don't use the aggregated timestamp from the summaries table, instead use the timestamp from the measurements table, this returns the true timestamp of when the last upload was inserted into the timeseries DB.
> fix: use proper measurement last uploaded

- core/middleware.py
- core/tests/test_middleware.py
re-enable in https://github.com/codecov/engineering-team/issues/1654
apparently this label was bringing down prometheus so we are nuking it for now. there are so many distinct UAs that prometheus suffers from a combinatorial explosion of possible label combinations
the skeleton daniel set up to add/test this custom label is still good, just gotta tweak the actual value of the label to scrub some of the minutiae from it
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by …
> disable user-agent prometheus label to decrease load

- codecov/settings_base.py
We want to ensure that `token`s don't get sent to Sentry when errors occur.
https://github.com/codecov/internal-issues/issues/419
This change will filter out the `_header` and `token_to_use` variables in a stacktrace frame so that the event doesn't push PII to Sentry. I'm currently filtering the whole `_header`, rather than just the `authorization` inside the `_header`. To enable that, I would need to enable `recursive` in the `EventScrubber`, which [might have potential performance implications](https://docs.sentry.io/platforms/python/data-management/sensitive-data/#event_scrubber). 
We might want to actually store the `denylist` in the `shared` repo (so that we can reuse this same list in `worker`).
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of …
> Add "token" variables to Sentry's EventScrubber denylist

- upload/tests/test_upload.py
- upload/tokenless/github_actions.py
Better errors for users
https://github.com/codecov/engineering-team/issues/1547
Hitting the rate limit for tokenless upload is a special case, adds special handling for this special case, and makes the upload failure more clear to the end user.
> add rate limit error handling to TokenlessGithubActionsHandler

- requirements.txt
This is to fix GHSA-2m57-hf25-phgg(https://github.com/advisories/GHSA-2m57-hf25-phgg) vulnerability.
https://github.com/codecov/internal-issues/issues/427
Update `sqlparse` to a non-vulnerable version.
> Update sqlparse to 0.5.0

- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
- upload/tests/views/test_bundle_analysis.py
- upload/tests/views/test_commits.py
- upload/tests/views/test_empty_upload.py
- upload/tests/views/test_reports.py
- upload/tests/views/test_test_results.py
- upload/tests/views/test_upload_completion.py
- upload/tests/views/test_uploads.py
- upload/views/bundle_analysis.py
- upload/views/commits.py
- upload/views/empty_upload.py
- upload/views/reports.py
- upload/views/test_results.py
- upload/views/upload_completion.py
- upload/views/uploads.py
fixes https://github.com/codecov/feedback/issues/344
Got some feedback, made me realize that this flow was being handled incorrectly. According to [Django's docs](https://www.django-rest-framework.org/api-guide/authentication/#custom-authentication),
> Typically the approach you should take is:
> - If authentication is not attempted, return None. Any other authentication schemes also in use will still be checked.
> - If authentication is attempted but fails, raise an AuthenticationFailed exception. An error response will be returned immediately, regardless of any permissions checks, and without checking any other authentication schemes.
I updated the flow to return `None` in a few places, instead of raising an error based on context that the function was assuming. 
Instead, they will …
> refine upload endpoint auth flow, add custom error message

- api/internal/tests/views/test_coverage_viewset.py
- codecov_auth/commands/owner/tests/test_owner.py
- codecov_auth/tests/unit/test_helpers.py
- codecov_auth/tests/unit/views/test_gitlab.py
- graphql_api/tests/test_branch.py
- graphql_api/tests/test_pull_comparison.py
- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/bundle_analysis/comparison.py
- graphql_api/types/comparison/comparison.py
- graphql_api/types/file/file.py
- graphql_api/types/me/me.py
- graphql_api/types/plan/plan.py
- graphs/tests/test_badge_handler.py
- services/bundle_analysis.py
- services/tests/test_components.py
- services/tests/test_repo_providers.py
- upload/tests/test_upload.py
When investigating another ticket, I saw that in our repo we sometimes used the same function name for multiple resolvers. This seemed like a clear code error, but then I realized that the resolver "bindable_field" decorator was added to things to maintain that uniqueness.
**However,** one place this wasn't accounted for was in tests. And I found some surprising results post fixing the duplicate test names. **That the tests with duplicate names were not running.** This seemed pretty concerning, since after fixing all the duplicate test names I saw there were 8 failing tests; ranging from a few months to a few years old.
This also made me realize that we don't have a linter on API (or worker / shared if I was looking at the code correctly), and might be something we want to look into …
> fix: Remove duplicate names for resolvers and tests

- graphql_api/tests/test_repository.py
- graphql_api/types/owner/owner.py
This is a follow up to https://github.com/codecov/engineering-team/issues/1253. 
On the front end, we want to show an error inside a page instead of letting `NetworkErrorBoundary` overwrite the whole page. Furthermore, we need repository information to conditionally render Coverage and Bundle Analysis setup tabs regardless of the owner's activation status. 
With this change, we do not throw an `OwnerNotActivated` error if the repo is not configured, enabling us to display onboarding tabs on the front end without throwing a page level error. 
More information about the project [here](https://www.notion.so/sentry/Seats-Allocations-Epic-733b98e82b2345c59e830e65d70ea8b1). 
Please note that this must be merged before https://github.com/codecov/gazebo/pull/2794.
Look, I get it. The entity doing …
>  Skip OwnerNotActivated error on unconfigured repos

- codecov/settings_base.py
Add cluster tag so we can tell where requests are in Sentry
> Add cluster tag for sentry tags

- api/internal/tests/test_permissions.py
- api/shared/permissions.py
Resolves https://codecov.sentry.io/issues/5131995858/?referrer=github_integration 
> fix: Resolve null owner

- codecov/settings_base.py
Fixes Playground from being blocked due to new CSP policies.
> Conent-security-policy allow GraphQL Playground to render

- upload/tests/test_upload.py
- upload/tokenless/github_actions.py
Showing the wrong string message before. This will push the retry timing to the user as to not block CIs while still displaying the correct timing.
fixes https://github.com/codecov/infrastructure-team/issues/346
- Sets wait to `None`, this will push the behavior to the user. Bash and uploader (I believe) currently do an exp backoff up to 10 seconds. Is this enough time? Absolutely not, but it will not run for 6 hours.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I …
> fix: update tokenless string

- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
- upload/helpers.py
Temporary logs for debugging OIDC auth
> adding logs for debugging

- .github/workflows/mypy.yml
Add mypy type checking in the GH CI. This does type checking for all files that are touched in the PR. This job runs at the same time the other main jobs run, however right now a failure on this does not block mergning (but it is encouraged to not fail the job), eventually it may start blocking merge to main. …
> Add GH action to do mypy check for patch

- dev.sh
- enterprise.sh
> Run correct migration command

- upload/helpers.py
The OIDC tokens coming from GitHub have a different audience. We can support more than 1 when we decode, so I'm proposing adding this one to match what we are receiving.
> add to audience for jwt decoding

- codecov/settings_dev.py
> Allow local dev build to run GQL Playground

- api/public/v2/component/views.py
- api/public/v2/tests/test_api_component_viewset.py
Resolves: https://github.com/codecov/internal-issues/issues/462
> fix: Resolve float() not accepting None value

- .github/workflows/ci.yml
- .github/workflows/mypy.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
Follow up to https://github.com/codecov/gha-workflows/pull/23, for API side GHA's
Simply version bumping to latest, non-deprecated workflow versions
> dev: update gha-workflows to latest

- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
- upload/helpers.py
Remove OIDC troubleshooting logs, keep one for low level monitoring
> remove troubleshooting logs

- api/internal/owner/serializers.py
- api/internal/tests/views/test_account_viewset.py
- billing/tests/test_views.py
- billing/views.py
- docker/Dockerfile-proxy
- services/billing.py
- services/tests/test_billing.py
We recently majorly bumped our stripe version and some api calls stopped working. This fixes the scheduled detail serializer one.
- adjusts tests + logic for scheduled phase serializer
> fix scheduled details key w/ stripe version upgrade

- services/billing.py
- services/tests/test_billing.py
Prorate must have been removed in the bump from stripe v2 -> v8. This is the new param for the same behavior
Fixes this error in stripe console: https://dashboard.stripe.com/logs?method[0]=post&path=%2Fv1%2Fsubscriptions%2F%3Aid&error_param=prorate&success=false&direction[0]=connect_out&direction[1]=self&created[preset]=7D
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in …
> fix: Use correct proration param for new stripe version

- api/internal/tests/views/test_account_viewset.py
- api/internal/tests/views/test_invoice_viewset.py
- billing/tests/test_views.py
- billing/views.py
- codecov/settings_dev.py
- codecov/settings_prod.py
- codecov/settings_staging.py
- plan/service.py
- plan/tests/test_plan.py
- requirements.in
- requirements.txt
- services/billing.py
- services/decorators.py
- services/tests/test_billing.py
This initiative stemmed from upgrading python to version 3.12, where in the process we bumped up our stripe version from 2.55.2 -> 8.9. This represented ~6.5 years of stripe versions and associated model updates in the process. Change log from stripe's website can be found [here](https://docs.stripe.com/upgrades).
After the initial merge of that PR, @adrian-codecov and I noticed that there were some issues coming in from sentry; which we thought to have fixed in https://github.com/codecov/codecov-api/pull/563. However, this didn't quell the issues; and in fact surfaced other issues in sentry where certain webhooks around subscription schedules were no longer being processed. Upon doing some additional investigation in the stripe dashboard, we realized that Stripe itself was using the 2017 …
> dev: Upgrade stripe version to latest and add typings

- api/public/v2/compare/views.py
- api/shared/permissions.py
- billing/tests/test_views.py
- codecov_auth/commands/owner/interactors/tests/test_get_is_current_user_an_admin.py
- graphql_api/types/config/config.py
- ruff.toml
- upload/helpers.py
- upload/views/bundle_analysis.py
- upload/views/commits.py
- upload/views/empty_upload.py
- upload/views/reports.py
- upload/views/upload_completion.py
Part of adding more lint rules to API / Shared / Worker -- https://github.com/codecov/engineering-team/issues/1716
This PR simply adds and fixes the "I" rules -- https://docs.astral.sh/ruff/rules/#isort-i
> dev: add isort rules for ruff and fix

- core/commands/commit/interactors/get_file_content.py
fixes: https://github.com/codecov/internal-issues/issues/463
Change the severity level from `log.exception` to `log.info`, showing on exception level doesn't offer much as there's no actionable things for when fetching a non existent path on GH (we always return null when that happens), instead it would only spawn a Sentry error. Downgrading the severity level removes the Sentry noise.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I …
> Lower log severity level to remove Sentry noise

- codecov/settings_base.py
- core/commands/pull/interactors/tests/test_fetch_pull_requests.py
- graphql_api/tests/test_owner.py
- graphql_api/tests/test_owner_measurements.py
- graphql_api/tests/test_plan.py
- graphql_api/tests/test_plan_representation.py
- graphql_api/tests/test_repository_measurements.py
- graphql_api/types/__init__.py
- graphql_api/types/commit/commit.py
- graphql_api/types/mutation/mutation.py
- ruff.toml
- services/yaml.py
- timeseries/tests/test_helpers.py
- upload/tests/test_upload.py
Part of the Ruff Enhancement epic, this adds all the "F" rules to our lint configuration for API, disabling a few super noisy ones that we can fix in individual PR's later. The benefit of doing it this way is we get ~40 rules "for free" that are on now checking our code :) At the cost of letting 4 of them be excluded til we have more bandwidth.
Rule list: https://docs.astral.sh/ruff/rules/#pyflakes-f
- The F Rules are all the "PyFlakes" rules that Ruff has configured
https://github.com/codecov/engineering-team/issues/1716
The rules we've mainly had to fix were around duplicate imports or duplicate keys in dicts. The rest we were already good on. Woohoo!
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In …
> dev: Enable most F rules for Ruff

- graphql_api/tests/mutation/test_cancel_trial.py
- graphql_api/tests/test_owner.py
- graphql_api/tests/test_user.py
- graphql_api/tests/test_views.py
- graphql_api/views.py
Gives insight into our GraphQL use
https://github.com/codecov/engineering-team/issues/1238
Adds 2 counters and 1 timer to our GQL endpoint, we should be able to see what queries are being used the most and if any are mad slow
The hardest part for me was trying to anticipate all the possible formats for our queries, to be able to parse and log them correctly in `set_type_and_name`. I have them listed in `test_query_metrics_extension_set_type_and_name`. If anyone knows of any other patterns we use, let me know and I'll build them in.
> add QueryMetricsExtension to graphql view

- .github/workflows/cache_cleanup.yml
- .github/workflows/ci.yml
- .github/workflows/mypy.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
Bumps the GHA Action workflows to 1.2.20
https://github.com/codecov/infrastructure-team/issues/375
> chore(ci): bump gha workflows to 1.2.20

- codecov_auth/helpers.py
- core/commands/commit/interactors/get_file_content.py
- graphql_api/tests/test_branch.py
- graphql_api/types/impacted_file/impacted_file.py
- graphql_api/views.py
- graphs/mixins.py
- graphs/views.py
- ruff.toml
- services/comparison.py
- services/profiling.py
- services/yaml.py
- webhook_handlers/views/github.py
Part of the Lint Enhancement epic, https://github.com/codecov/engineering-team/issues/1716, this PR aims to add a majority of the E rules to our ruff setup.
The ruff "E" rules are the "error" rules for the pycodestyle package. A majority of the fixes in this PR were for rules E721 and E722, around using type == instead of instanceof() and using bare excepts vs. explicit excepts.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm …
> dev: Enable most "E" rules for Ruff

- codecov_auth/tests/unit/views/test_logout.py
- codecov_auth/views/logout.py
Allows logout by POST request. Part one of a three-part CSRF vuln fix with our existing GET logout strategy.
Closes https://github.com/codecov/internal-issues/issues/486
> feat: Allow logout by POST request

- services/billing.py
- services/tests/test_billing.py
Customer issue around prefilled email being prefilled but incorrect, stripe docs don't seem to allow changing of prefilled email when creating stripe session so we're looking to remove the prefill altogether.
Related Docs: https://docs.stripe.com/api/checkout/sessions/create
N/A
This PR simply removes email from being passed into the stripe checkout session, but still defaulting the customer value if it exists.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain …
> fix: Remove prefilled email for customer if exists

- graphql_api/tests/test_components.py
- graphql_api/types/owner/owner.graphql
- graphql_api/types/owner/owner.py
With the completion of https://github.com/codecov/engineering-team/issues/355, we can safely remove the resolver from the API. This PR closes https://github.com/codecov/engineering-team/issues/356.
> Remove repository deprecated resolver 

- graphql_api/tests/test_invoice.py
- graphql_api/types/invoice/invoice.graphql
- graphql_api/types/invoice/invoice.py
Removes the unused invoice fields that aren't being referenced anymore in gazebo. Since we're exposing all the fields in GQL now, it is increasingly important to only expose fields that we intend to use.
closes https://github.com/codecov/engineering-team/issues/1847
Went through gazebo and confirmed the fields that were being used when pulled off the invoice model. There were 6 unused fields:
- invoicePDF
- currency
- customerAddress
- amountRemaining
- periodStart
- customerShipping
Of these, I removed invoicePDF, amountRemaining and customerShipping. I decided it maybe worthwhile keeping both currency and customerAddress since we have some initiatives coming up that will need those fields shown on the UI
Look, I get it. The entity doing business as "Sentry" was incorporated in the State …
> chore: Remove unused Invoice GQL fields

- codecov_auth/tests/unit/views/test_logout.py
- codecov_auth/views/logout.py
Removes the logic to handle GET requests at `/logout`. This is the final part of the transition from GET to POST on the logout endpoint.
Closes https://github.com/codecov/internal-issues/issues/488
Closes https://github.com/codecov/internal-issues/issues/391
> chore: Remove GET method handler for /logout endpoint

- billing/tests/test_views.py
- billing/views.py
Want to prevent some noisy sentry exceptions from occurring if we can help it. This PR fixes the following:
- Subscription Deletion error when user subscription has already been deleted. This may occur when a webhook gets retried after a subscription has already been deleted off a user
- Subscription schedule created/updated failing to grab obo_organization:
- This occurs when we're pulling obo_organization off metadata in an unsafe way. We want to use .get() to protect in the event it is null.
- Because those are only being used in the logs, I'm not too worried about any unintended behavior.
Sentry Links:
https://codecov.sentry.io/issues/4271768168/?project=5215654&project=4165036&project=4505562661847040&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+billing&referrer=issue-s …
> fix: Some uncaught exceptions related to billing

- services/billing.py
- services/tests/test_billing.py
Adds the VAT information field to the stripe checkout session, this is to allow user's part of businesses to accurately represent their tax information, particularly for users outside of the US.
Related stripe docs: https://docs.stripe.com/tax/checkout/tax-ids
Closes https://github.com/codecov/engineering-team/issues/1868
**NOTE:** This doesn't affect anything outside of the stripe customer object, or anything outside of the stripe session.
https://github.com/codecov/codecov-api/assets/159853603/084974c9-918f-4831-bb19-84b66df8462b …
> feat: Add VAT to checkout session

- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.py
Updates `isCurrentUserActivated` resolver to no longer count admins as activated when they don't have a seat.
Closes https://github.com/codecov/internal-issues/issues/502
After this change, admins will see the following when trying to access a private repo when not activated:
> fix: Prevent org admins from being activated even without seat

- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
- upload/tests/views/test_commits.py
- upload/tests/views/test_reports.py
- upload/tests/views/test_uploads.py
- upload/views/commits.py
- upload/views/reports.py
We don't want to make GH API calls when doing tokenless anymore
https://github.com/codecov/engineering-team/issues/1574
- Remove GitHub API calls from TokenlessAuthentication
> Tokenless V3

- codecov/settings_base.py
- codecov_auth/tests/unit/views/test_gitlab.py
- codecov_auth/tests/unit/views/test_gitlab_enterprise.py
- codecov_auth/views/gitlab.py
Test locally with adding `gitlab_scopes` to the  `config/codecov.yml` file in umbrella-hat.
> gitlab oauth scope setting

- api/internal/owner/views.py
- api/internal/tests/views/cassetes/test_account_viewset/AccountViewSetTests/test_update_billing_address.yaml
- api/internal/tests/views/test_account_viewset.py
- services/billing.py
- services/tests/test_billing.py
Part of the Q2 billing epic, particularly around updates for edit billing details, this PR aims to add a new service function around updating a user's billing address.
This function is very similar to the email address function, the main difference being the data payload being pulled from the API request and the payload being passed into the stripe customer modify function.
Closes https://github.com/codecov/engineering-team/issues/1863
For now, this endpoint isn't being used anywhere, but it will be used in the useUpdateBillingAddress gazebo hook added in this PR: https://github.com/codecov/gazebo/pull/2940. That hook is currently hard coded to use sentry's company address.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as …
> feat: Add Update Billing Address service function

- api/internal/owner/views.py
- api/internal/tests/views/test_account_viewset.py
- services/billing.py
- services/tests/test_billing.py
This updates the existing update_billing_address function to actually update the stripe default payment method billing details, as well as the customer billing address.
Stemmed from doing some local testing with the new address component where i saw the default_payment_method billing details address wasn't being updated when we were updating the users address. Now we update both the customer as well as the payment method address with this set of changes.
Most of the review is UT updates, but for the stripe stuff we are doing three things:
- Retrieve the stripe customer details, and pull off the default payment method from that detail
- modify the default payment method address fields with the address fields being passed in
- update the customer object's address itself with the address …
> fix: Address Glue Updates for modifying default payment method

- api/internal/tests/views/cassetes/test_account_viewset/AccountViewSetTests/test_update_payment_method.yaml
- api/internal/tests/views/test_account_viewset.py
- services/billing.py
- services/tests/test_billing.py
Stemmed from this sentry feedback that came in: https://sentry.slack.com/archives/C04LZKE8RMJ/p1718994052609629
Long story short, a stripe subscription will use it's default payment method if exists, before using a customer's default payment method. Because we give the default payment method to a subscription at the time of creation, when a user goes to update their default payment method it doesn't update on the subscription, leading to some weird behavior
The fix then is to also update the default payment method on the subscription to the updated payment method, which is also the payment method shown on the portal for the user.
Relevant stripe doc:
https://docs.stripe.com/api/subscriptions/update#update_subscription-default_payment_method
- Calls out when this payment method is used vs. …
> fix: Update default payment method on subscription for user

- codecov_auth/authentication/helpers.py
- codecov_auth/authentication/repo_auth.py
- codecov_auth/tests/unit/test_repo_authentication.py
Some methods were never finished.
> fix: Fix GlobalUploadToken auth

- graphql_api/actions/measurements.py
- graphql_api/tests/test_bundle_analysis_measurements.py
- services/bundle_analysis.py
closes: https://github.com/codecov/engineering-team/issues/1976
Make it so that when fetching measurements for trends, if the start date range doesn't have any value, then we look back further until we find the first instance of a measurement point. Then we use that point's value as the value of the start date range. Otherwise it becomes ambiguous if the measurement ID has no measurement at all in history or that the start date has no measurement.
With this if the start date range is still null it means there was never any measurements before the start date. If the start date range is not null there were measurements carried over from the further past.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In …
> bundle analysis: update trend measurement compute

- api/internal/owner/views.py
- api/internal/tests/views/test_account_viewset.py
- services/billing.py
- services/tests/test_billing.py
Fixes [bug](https://github.com/codecov/engineering-team/issues/2013) where updating name in UI doesn't work by modifying the update_billing_address view to accept a name parameter. Corresponding change in Gazebo to be merged first. Arguably this could be done better, but we're just trying to fix the bug right now. Will bring up with Ajay when he's back.
Tested on staging with the Gazebo change, all is working as expected!
> fix: Update name in update_billing_address view

- requirements.in
- requirements.txt
Patch urllib3 
This closes https://github.com/codecov/internal-issues/issues/550
> [Vuln] Bump urllib3 to >= 1.26.19

- graphql_api/tests/test_commit.py
- graphql_api/types/bundle_analysis/report.py
- graphql_api/types/enums/__init__.py
- graphql_api/types/enums/enum_types.py
- graphql_api/types/enums/enums.py
- services/bundle_analysis.py
closes https://github.com/codecov/engineering-team/issues/1898
passes the GQL filter options downstream to use the filtering capabilities provided in shared modules.
> bundle analysis: add asset filtering

- webhook_handlers/tests/test_github.py
- webhook_handlers/views/github.py
ticket: https://github.com/codecov/internal-issues/issues/519
Saves when we receive a request to suspend/unsuspend an app installation
> feat: save if apps are suspended

- codecov/settings_base.py
Fixes: https://github.com/codecov/engineering-team/issues/178
Depends on: https://github.com/codecov/shared/pull/268
> fix: remove all usage of segment

- billing/tests/test_views.py
- billing/views.py
Fixes infinite loop introduced in https://github.com/codecov/codecov-api/pull/630 which has meant us spamming the Stripe API constantly.
> fix: Prevent infinite loop in update_payment_method logic

- core/commands/pull/interactors/fetch_pull_request.py
- core/commands/pull/interactors/tests/test_fetch_pull_request.py
- graphql_api/tests/test_pull.py
It's possible with a combination of not having webhooks and temporary errors when
fetching info from the git provider that a PR will be left forever open.
One solution is to make the PR view trigger a sync_pull task in the background.
Notice that for the person that is actually viewing the PR it will probably be out of date,
but if they refresh the page it will eventually be updated.
closes: https://github.com/codecov/internal-issues/issues/513
> feat: trigger PR sync

- codecov_auth/commands/owner/interactors/save_okta_config.py
- codecov_auth/commands/owner/interactors/tests/test_save_okta_config.py
- codecov_auth/commands/owner/tests/test_owner.py
- codecov_auth/tests/factories.py
- graphql_api/tests/mutation/test_save_okta_config.py
- graphql_api/types/mutation/save_okta_config/save_okta_config.py
- upload/tests/test_throttles.py
> fix un-formatted code + revert change to Owner Factory

- codecov_auth/authentication/repo_auth.py
- upload/tests/views/test_upload_completion.py
This code introduced an issue when it was added, sentry entry [here](https://codecov.sentry.io/releases/production-release-252b887/?project=5215654). lots of responses were getting a `KeyError` because they didn't have the format that was expected. 
Makes the logic in the function much more cautious, does several checks instead of making assumptions
> be more flexible with responses coming through repo_auth_custom_exception_handler

- graphql_api/actions/measurements.py
- graphql_api/tests/test_bundle_analysis_measurements.py
- graphql_api/types/bundle_analysis/base.graphql
- graphql_api/types/bundle_analysis/base.py
- requirements.in
- requirements.txt
- services/bundle_analysis.py
- Make the `after` arg as optional, if not present will fetch from the first commit measurement datapoint.
- `BundleAsset.bundleData.size.gzip` now returns true gzip size if available (via version 2 of bundle stats file) or fallbacks to old calculation (ie size/1000)
closes https://github.com/codecov/engineering-team/issues/1928 …
> bundle analysis: measurements optional "after" data and fetch asset gzip size from DB

- codecov_auth/tests/unit/views/test_github.py
- codecov_auth/views/github.py
Removes the code that sets the github session expiry cookie.
We are going to try a different approach to come in a future PR.
Closes https://github.com/codecov/engineering-team/issues/2025
> fix: Remove session expiry cookie

- graphql_api/tests/test_components.py
- graphql_api/types/commit/commit.py
- services/components.py
- services/yaml.py
Fix call to `commit_components` to use the `Owner` type 
https://github.com/codecov/internal-issues/issues/452
It was originally passing in a `User` object, but actually needed an `Owner` object. Getting the commit was (silently) failing on `service not found` because a service is not associated with a `User`.
I tested this locally and it seems to get the YAML components for the commit now. Previously, it would default to the repo YAML, which would be unstable based on whether the repo YAML is set (or updated during sync).
I also added a log so that this shouldn't silently fail.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some …
> Fix call to `commit_components` to use the right type

- api/public/v2/test_results/permissions.py
- api/public/v2/test_results/serializers.py
- api/public/v2/test_results/views.py
- api/public/v2/tests/test_test_results_view.py
- api/public/v2/urls.py
- codecov-api
- reports/tests/factories.py
https://github.com/codecov/engineering-team/issues/1975
> feat: Public test results API 

- codecov/settings_base.py
- graphql_api/tests/test_commit.py
- graphql_api/types/bundle_analysis/base.graphql
- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/bundle_analysis/report.graphql
- graphql_api/types/bundle_analysis/report.py
- requirements.in
- requirements.txt
- services/bundle_analysis.py
closes https://github.com/codecov/engineering-team/issues/2035
Fetches whether a bundle report is cached or not (`BundleReport.isCached`) and whether if there are any reports in the bundle analysis report that is cached (`BundleAnalysisReport.isCached`)
> Update GQL to return whether bundles are cached

- graphql_api/types/owner/owner.py
The `determine_entity_redis_key` requires both args to be specified even if one of them is None. Updating function call to match the signature. 
> [fix] Pass extra param in resolver function 

- api/internal/repo/utils.py
- api/internal/repo/views.py
- api/internal/tests/views/test_repo_view.py
- core/commands/repository/interactors/encode_secret_string.py
- core/commands/repository/interactors/regenerate_repository_upload_token.py
This PR removes old REST endpoints for 
- EncodeSecretString
- Regenerate Repo Upload token 
- Erase Repo 
It also contains a fix to an edge case to update viewable repositories so the UI can see all repos in the org, not just those authored by the logged in user.  …
> Remove old REST repo endpoints and update new GQL mutations 

- graphql_api/tests/test_pull.py
- graphql_api/types/pull/pull.py
closes: https://github.com/codecov/engineering-team/issues/2040
Handles a case where the PR was created without any uploads because all bundles from the build is cached. Instead of showing a "no commit error" we will instead show the parent bundle report as it implies everything was cached and carried over to the head commit. …
> bundle analysis: when no head commit fall back to report base report

- codecov_auth/admin.py
Adding pages for new models. actions/widgets (to call tasks or scripts) will come later
https://github.com/codecov/engineering-team/issues/2058
> Add django admin pages for new models

- graphql_api/tests/test_commit.py
- services/bundle_analysis.py
closes https://github.com/codecov/engineering-team/issues/1925
Returns count of number of modules of a bundle report with filtering applied.
> bundle analysis: fix module count computation

- docker/Dockerfile
`setuptools` was updated today and the new version is causing problems with our build process. Pinning this to an older version for now.
> Pin setuptools to a version that works

- codecov_auth/tests/unit/views/test_okta.py
- codecov_auth/tests/unit/views/test_okta_mixin.py
- codecov_auth/views/okta.py
- codecov_auth/views/okta_mixin.py
- requirements.in
- requirements.txt
Refactoring this so that it is more easily shared. Split this from [part 2](https://github.com/codecov/codecov-api/pull/685) to make reviewing both parts easier. See Part 2 for more context in how this refactor will be used.
https://github.com/codecov/engineering-team/issues/1988
This moves some of the shared code that will be common in all Okta implementations to a new `mixin` that can be shared across both Views. 
* I added Pydantic to better type check the responses coming from Okta (and better document what is in the responses). …
> [Okta Login] Part 1: Refactoring existing Okta code

- upload/helpers.py
- upload/tests/views/test_commits.py
- upload/tests/views/test_reports.py
- upload/tests/views/test_uploads.py
- upload/views/commits.py
- upload/views/legacy.py
- upload/views/reports.py
- upload/views/uploads.py
I'm comparing the calls bw Shelter + API upload endpoints. I want to make sure the position bw them and Shelter's are the same, so we can accurately map if calls are getting lost in the switch
> Adjust the metrics to better match/represent shelter calls

- billing/tests/test_views.py
- billing/views.py
- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.graphql
- graphql_api/types/owner/owner.py
- requirements.txt
Part of billing updates, https://github.com/codecov/engineering-team/issues/1814, to better show users who are currently in delinquency status, need to expose this model property in GQL to show on gazebo via query.
Also fixes a couple typos (including one on a test lol) of the word "delinquent"
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry …
> feat: Expose delinquent status on owner in gql

- codecov_auth/admin.py
- codecov_auth/tests/test_admin.py
Gives us a method to do the initial setup when an Account is created. This action will create the link between the Account object and the User object for any Owner who is a `plan_activated_user` on any of the Organizations linked to the Account.
Can be run multiple times safely (in case it errors or times out)
Won't do the link if the Account doesn't have enough seats
For "auditing" its behavior - it gives messages about how many Users and AccountUsers were created. You can see the Users linked to the Account on the Account edit page (when you click into an Account on the admin). You can remove a AccountUsers connection on the User admin page.
Uses https://github.com/codecov/shared/pull/295
part of https://github.com/codecov/engineering-team/issues/2058
> add action to link users to accounts

- api/internal/owner/serializers.py
- api/internal/tests/views/test_account_viewset.py
Part of https://github.com/codecov/engineering-team/issues/1814, originally thought we needed to update the GQL serializer, but I realized we're actually using the account-details endpoint for that component, so we should also update that serializer as well.
Long term we can swap over to the GQL serializer, but this will reduce FE code in the short term until we swap over. (And an extra network call as well)
Couple screenshots below showing null and boolean response coming back
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to …
> feat: Add delinquent to account details serializer

- webhook_handlers/tests/test_github.py
- webhook_handlers/views/github.py
This PR closes https://github.com/codecov/internal-issues/issues/493
We query for an owner during webhook events using `get_or_create` based on their service, service_id, and username. The combination of service and service_id serves as a unique key. We have cases where we have entries in the users table with no username so the `get` part of the `get_or_create` would return `None` and the `create` part attempts to create a new entry but fails due to violating the constraint. This change moves the username field to be a default argument.  …
> [fix] Fix duplicate key value violates unique constraint "owner_service_ids" Sentry errors 

- upload/tests/views/test_test_results.py
- upload/views/test_results.py
previously the test results upload endpoint did not require a branch field in the data included with the upload but it also did not allow null values for the branch field, so in v0.7.3 of the CLI when we added the branch field to the upload, some uploads were broken because the CLI would not be able to detect a branch and so the branch field would be set to None.
This change modifies the endpoint to accept null values for the branch and if the endpoint is creating the Commit object in the database and the branch field is set to null then it will set the branch field of the commit to the default branch of the repo it's targetting.
> fix(test results): accept null branch and add default branch

- codecov_auth/tests/unit/views/test_okta_cloud.py
- codecov_auth/urls.py
- codecov_auth/views/okta_cloud.py
This adds the login endpoint for uses to sign into Okta for specific orgs/account.
Depends on Part 1: https://github.com/codecov/codecov-api/pull/691
https://github.com/codecov/engineering-team/issues/1988
Note that this is _not_ to authenticate the user. We check that the user has already authenticated via another mechanism (i.e. Github). This adds extra permissions for organizations that want extra level of security to see private repos.
The authentication flow looks something like this:
```mermaid 
sequenceDiagram
User->>+Codecov: /login/okta/{service}/{org}
Codecov->>+Okta: if not signed in, then redirect them to okta.com/oauth2/v1/authorized
Okta->>+User: shows the user the Okta sign-in UI
User->>+Okta: enters in credentials and signs in
Okta->>+Codecov: sends back credentials info …
```
> [Okta Login] Part 2: Add Okta Login API for Organizations/Account 

- codecov_auth/admin.py
- codecov_auth/tests/test_admin.py
Realized that the delete buttons weren't doing what I wanted them to do - I wanted them to delete the _connection_ not the object. Added these customizations to prevent related objects from being deleted by accident.
https://github.com/codecov/engineering-team/issues/2060
added tests, and these changes were thoroughly tested on my local
> refine admin experience

- core/commands/repository/interactors/fetch_repository.py
- core/commands/repository/interactors/tests/test_fetch_repository.py
- core/commands/repository/repository.py
- core/commands/repository/tests/test_repository.py
- graphql_api/actions/repository.py
- graphql_api/tests/test_current_user_ariadne.py
- graphql_api/tests/test_owner.py
- graphql_api/types/me/me.py
- graphql_api/types/owner/owner.py
- requirements.in
- requirements.txt
- upload/views/legacy.py
For organizations with `enforced` Okta configurations, we only want to show the public repos for the user. They will need to be authenticated to get access to private repos on our UI.
ref: https://github.com/codecov/engineering-team/issues/1992
Filters out repos on the GraphQL endpoint for orgs that the user is not authenticated with for various queries that requests repository information.
We aren't filtering out the repos for public API endpoints. This is because these endpoints auth through token authentication are (likely, sometimes) to be used in some automated pipeline where Okta doesn't make sense.
I would like some feedback on whether there's any other API endpoints I'm missing that should have repos filtered. 
Look, I get it. The entity doing business as "Sentry" was incorporated …
> Filter out private repos with Enforced Okta setting

- core/commands/repository/interactors/regenerate_repository_upload_token.py
- graphql_api/tests/mutation/test_regenerate_repository_upload_token.py
Fix customer issue and revert to old behaviour. 
> [fix] Update regen repo upload token mutation to work on inactive repos

- graphql_api/types/comparison/comparison.py
- services/comparison.py
When viewing the pulls page, user may run into an error with hasDIfferentNumberOfHeadAndBaseSessions erroring out due to a github API call when fetching the "fresh" head_report here: https://github.com/codecov/codecov-api/blob/20b3a8199d43e5f96eaa3fd39cd8bae6f06c833e/services/comparison.py#L716
When discussing with @adrian-codecov, we thought that this check may not actually be needed; and that the implication of having a "stale" head report doesn't necessarily change the boolean "hasDifferentNumberOfHeadAndBaseSessions" value meaningfully.
Additionally, we found[ some logic related to CFF](https://github.com/codecov/codecov-api/blob/20b3a8199d43e5f96eaa3fd39cd8bae6f06c833e/services/comparison.py#L723-L728) (Carry Forward Flags) that needs to be revisited as well, since right now we're …
> fix: hasDifferentNumbersofHeadAndBase short term fix

- upload/helpers.py
- upload/views/empty_upload.py
- upload/views/legacy.py
The legacy endpoint takes on reports from different versions, v2/3/4. We're trying to compare the in/out traffic from shelter and api, but shelter only supports (and only means to) v4, so we want to add another tag to filter v4 requests
> add version to legacy metrics

- upload/helpers.py
- upload/views/legacy.py
I added the version here, https://github.com/codecov/codecov-api/pull/717, but didn't realize the "version" keyword was already in use. Changing to upload version
> Add proper key to separate upload version

- upload/helpers.py
- upload/tests/test_upload.py
fixes https://github.com/codecov/internal-issues/issues/567
looking in Google Logs Analyzer, all of these values are one of:
- `https://dev.azure.com/username/`
- `https://username.visualstudio.com/`
- URL-encoded versions of the above
this PR adds a regex validator to ensure that arbitrary URIs are not provided
(Heads up - this is "merge when ready")
> add regex validation for azure server_uri param on v4 upload endpoint

- docker/Dockerfile.requirements
If I see things correctly, `codecov-ribs` is the only Rust-based dependency in the dependency graph, which by now is being consumed as a prebuilt binary.
Thus there should be no need to have a Rust toolchain installed in this docker image.
> Remove Rust from the Docker image

- graphql_api/helpers/connection.py
- graphql_api/types/repository/repository.py
- graphql_api/types/test_results/test_results.py
- utils/test_results.py
There was a bug with the test results graphql endpoint that when ordering was set, the second page and onwards would be empty.
This was due to the need for part of the ordering parameter to have compeletely unique values due to how the CursorPagination class works.
Closes https://github.com/codecov/engineering-team/issues/2168
> fix(test_results): graphql endpoint ordering bug

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Saw this on my App, hook returning internal server error.
Should hopefully [fix these sentry issues](https://codecov.sentry.io/issues/?project=5514400&project=5215654&project=4165036&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+ratelimit&referrer=issue-list&statsPeriod=7d)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …
> fix: isGithubRateLimited can return null

- api/internal/owner/serializers.py
- api/internal/owner/views.py
- api/internal/tests/views/test_account_viewset.py
- requirements.in
- requirements.txt
There are certain fields that are controlled by the Account if the Org has an Account. These changes make it so that when you view the `plan` or `member` page, if your Org has an Account, you see the details from the Account, not the Org.
Also adds logic to make sure that a user cannot do self-serve functions (changing their plan) if they have an Account. The current implementation of Accounts are that they are sales-led only, they have to change their plan details through their sales contact, and if they were able to change the plan on a single Org in the Account, weird things would happen. So if they have an Account we want to block these actions.
> update account-detail endpoint to show info on Account if the Org has an Account

- graphs/views.py
Fixes sentry issue: https://codecov.sentry.io/issues/2768942613/?environment=epic&environment=dd&environment=enova&environment=mailchimp&environment=production&environment=roblox&environment=snowflake&environment=prodvana&project=5514400&project=5215654&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=9
We just want to default a numerical value in the event both the .get() and the default from the get are non-integer values.
The sentry issue is complaining that the default value is '', and if you do '' or 100 (like in the PR), we will use 100
These eventually bubble up to here: https://github.com/codecov/codecov-api/blob/c9bc2c82a682f02cc6e88e804290d11eabf4ca22/graphs/helpers/graph_utils.py#L102-L117
Closes …
> fix: Default height/width to 100% if either doesn't exist

- graphql_api/actions/measurements.py
- requirements.in
- requirements.txt
- services/bundle_analysis.py
The `shared` code completely removed the `db_session` on the `BundleAnalysisReport`. Thus there is no need to `close` those sessions and for these cleanup methods to exist.
related to https://github.com/codecov/internal-issues/issues/650
Depends on https://github.com/codecov/shared/pull/309
> Remove obsolete `cleanup` from BundleAnalysis

- codecov_auth/commands/owner/interactors/cancel_trial.py
- codecov_auth/commands/owner/interactors/start_trial.py
- codecov_auth/commands/owner/interactors/tests/test_cancel_trial.py
- codecov_auth/commands/owner/interactors/tests/test_start_trial.py
This PR aims to fix the IDOR hole mentioned in https://github.com/codecov/internal-issues/issues/646 where users can start or cancel trials even if they don't belong to the organization
To fix, we simply check to see that the user is part of the organization in the validate step prior to executing the mutation
Closes https://github.com/codecov/internal-issues/issues/646
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry …
> fix: Add validation for trial start/cancel for user in calling org

- codecov/settings_prod.py
- codecov/settings_staging.py
- webhook_handlers/views/github.py
When looking through sentry issues, I saw one related to request body exceeding the max memory size, with [~800 events in the last 30 days](https://console.cloud.google.com/logs/query;query=jsonPayload.message%3D%22Request%20body%20exceeded%20settings.DATA_UPLOAD_MAX_MEMORY_SIZE.%22;summaryFields=jsonPayload%252Fusername:false:32:beginning;cursorTimestamp=2024-08-08T16:34:48.355847094Z;duration=P30D?project=genuine-polymer-165712&authuser=1&rapt=AEjHL4NstEBFMmkju6lWhfES-l36CF3N8JNO5BmHLfqmHGs074dXJ2LmKSBNlH3qpCYA1MLpwrBaPiHMeOfmV0cDHg1WIlGWtopDp8GaSYIUC2SlWj6bBWI). Looking at the stack trace, these all looked to be coming from the github webhook handler. Checking our current limit in API, it looks like our max size we currently allowed was set to 15MB; but then looking at the max github …
> fix: Update DATA_UPLOAD_MAX_MEMORY_SIZE to 25 MB

- codecov_auth/middleware.py
We want to improve impersonation logs for the security team.
https://github.com/codecov/engineering-team/issues/1850
Adds extra email field for the staff user to the Panther impersonation logs.
> Add extra information to the impersonation logs

- graphql_api/tests/test_plan.py
- plan/service.py
When an Org has a license, the `plan_user_count` on their Org is not accurate, the `number_allowed_users` from the license should be used for this value. Some self-hosted or DEC customers are getting a false positive on an alert that checks the seat count, because it's not checking whether they have a license.
https://github.com/codecov/internal-issues/issues/679
When checking `plan_user_count` in PlanService, if they have a license, return `number_allowed_users` as the value, which is the correct paid seat count for an Org with a license.
> update plan service to work with self-hosted and DEC

- graphql_api/tests/test_plan.py
- plan/service.py
- services/self_hosted.py
- services/tests/test_self_hosted.py
We calculate seats differently for self-hosted and DEC, this updates the `has_seats_left` on `PlanService` to work correctly for self-hosted and DEC.
https://github.com/codecov/internal-issues/issues/679
The function was comparing the total seat count to the number of active users for the Org. With self-hosted and DEC, it will now compare total seat count to the number of unique users across all Orgs.
> update has_seats_left on plan service to work properly with self-hosted and DEC

- core/admin.py
- webhook_handlers/tests/test_gitlab.py
- webhook_handlers/tests/test_gitlab_enterprise.py
- webhook_handlers/views/gitlab.py
Refine the flow, use webhook_secret if it is set on repo.
https://github.com/codecov/internal-issues/issues/359
> update gitlab webhook flow

- billing/views.py
Couple quick .get() instead of direct key access for obo_organization
> dev: safely retrieve obo_organization for billing webhooks

- graphql_api/tests/test_test_result.py
- graphql_api/types/test_results/test_results.py
We collate the class name and test case name parsed from the JUnit XMLs with a special char `\x1f`, we want to display it as a space though. Perhaps this logic should occur in Gazebo?
> fix: replace special char in test name with space

- codecov_auth/views/okta_cloud.py
This is to appease the static analysis security scan to ensure that we are not directly using user input for redirect.
https://github.com/codecov/internal-issues/issues/645
Change which username and service we're using to generate the app url.
> Get app_redirect_url from owner object rather than request params

- codecov_auth/commands/owner/interactors/tests/test_cancel_trial.py
- codecov_auth/commands/owner/interactors/tests/test_get_uploads_number_per_user.py
- codecov_auth/commands/owner/interactors/tests/test_start_trial.py
- codecov_auth/management/commands/set_trial_status_values.py
- codecov_auth/management/commands/tests/test_set_trial_status_values.py
- plan/service.py
- plan/tests/test_plan.py
- upload/tests/test_upload.py
- upload/tokenless/azure.py
- upload/tokenless/github_actions.py
- upload/tokenless/tokenless.py
- upload/tokenless/travis.py
Saw there was a python warning in my IDE that utcnow is a deprecated function
Related blog post from late 2023 -- https://blog.miguelgrinberg.com/post/it-s-time-for-a-change-datetime-utcnow-is-now-deprecated
correct way now is to use .now(UTC) instead; all the changes in this PR are basically just find and replace and import UTC when necessary
Relevant stackoverflow post: https://stackoverflow.com/questions/15307623/cant-compare-naive-and-aware-datetime-now-challenge-datetime-end for why we had to chain .replace(tzinfo=None) to some calls
Remove deprecation warnings related to utcnow()
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, …
> chore: Remove deprecated utcnow fn

- api/internal/tests/views/test_repo_view.py
- core/tests/factories.py
- requirements.in
- requirements.txt
- services/report.py
- services/tests/test_archive.py
https://github.com/codecov/internal-issues/issues/515
https://github.com/codecov/shared/pull/329
this field is bugged and, as far as i can tell, unused. see ticket + shared PR for details
> remove session_totals field from report json

- codecov_auth/commands/owner/interactors/save_okta_config.py
- codecov_auth/commands/owner/interactors/tests/test_save_okta_config.py
- codecov_auth/tests/unit/views/test_okta_cloud.py
- codecov_auth/views/okta_cloud.py
This removes trailing slashes from their usage in the code, and also from saving to the database. This should fix issues where we validate the payload from Okta with the ISS URL (they send it without trailing slashes).
https://github.com/codecov/internal-issues/issues/709
1. Strip the URL of trailing slashes at the point of using the URL
2. Strip the URL of trailing slashes before saving to the DB
We _probably_ don't need both, but having both will just be safer. …
> Strip Okta ISS URL of trailing slashes

- core/commands/repository/interactors/regenerate_repository_upload_token.py
The front end sends the current org selected as part of the `RegenerateRepositoryUploadToken` mutation.
We are running into cases where a different repo with the same name can have its token updated as we are updating the first repo amongst all viewable repositories for a given org. 
This PR adds a check to only select from repos that are _**authored**_ by that org. 
This fixes https://github.com/codecov/engineering-team/issues/2377
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> [fix] Ensure repo token regeneration only checks for repos authored by current org

- upload/helpers.py
- upload/tests/views/test_uploads.py
When getting the enterprise url for oidc auth, remove trailing slashes if any exist
https://github.com/codecov/internal-issues/issues/702
> check for trailing slashes

- upload/tests/views/test_test_results.py
- upload/views/test_results.py
Saw sentry issue come in, we added a guard for bundle_analysis similarly here: 
https://github.com/codecov/codecov-api/blob/1c2b6a8ed0568ee45af238d46f1576bb9ae90fb9/upload/views/bundle_analysis.py#L92-L93
Closes https://github.com/codecov/engineering-team/issues/2406
Fixes this sentry issue:
https://codecov.sentry.io/issues/5759286173/?environment=dd&environment=enova&environment=epic&environment=production&environment=roblox&environment=snowflake&project=5215654&project=5514400&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=2
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to …
> fix: guard no repo for test_results

- rollouts/__init__.py
- upload/views/reports.py
> soft ripping out PreProcessUpload task

- core/admin.py
- core/tests/test_admin.py
It's a common issue to have `null=True` or a `default_value` _without_ `blank=True` on a field in a django model. This causes a conflict in forms, which interprets the field as `required` even though you intend for the value to be `null` or the `default_value` set on the field. In my case, I was trying to clear out the `webhook_secret` field, but my changes were blocked because the `webhook_secret` cannot be blank, therefore there was no way to get it back to the `null` value I wanted, which is allowed in the database.
part of https://github.com/codecov/internal-issues/issues/366
I need to be able to delete the webhook_secret, this was not allowed by the form. These changes allow me to clear out that field, fixed it on a few other fields on the model as well so that it behaves closer to …
> fix Repo form in django admin

- core/signals.py
The token cacher is seemingly skipping some repositories getting saved in firestore. This is an attempt to log the start/error of any of these transactions to give me more visibility on the issue
> log repo signals

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.py
We're getting a bunch of errors in sentry regarding rate limits. 
After looking at the logic, I believe it has to do with using the wrong owner in certain occasions. This PR addresses that.
> 2446 address rl bug

- plan/service.py
- plan/tests/test_plan.py
Gazebo uses PlanService to gate user actions, and can block a user from accessing private repos based on the `has_seats_left` property on the `Org`. Plan service is not aware of `Accounts` - we thought a user on a sales-led plan wouldn't interact with PlanService, that assumption was incorrect.
https://github.com/codecov/engineering-team/issues/2268
Updates PlanService to check for presence of an Account then pull the numbers/settings from the Account rather than the Org for read-only purposes. still no write 🙃
> Update plan service to work with Accounts

- graphql_api/actions/owner.py
- graphql_api/tests/test_plan.py
In django, adding a dot notation to an object does a db query, so when I added `self.current_org.account` to `PlanService`, this adds a db call. This breaks an async flow, which gazebo uses. Solution is to do a prefetch_related when we get the `current_org` so that `self.current_org.account` does not call the db.
https://codecov.sentry.io/issues/5771897965/events/a320d20a70534672bac6ce9db263f4e0/
> query errors during async process

- codecov_auth/admin.py
- codecov_auth/tests/test_admin.py
Enterprise orgs often want to clean up their stale users to free up seats. This implements such an "admin" action.
- fixes https://github.com/codecov/engineering-team/issues/2101
- fixes https://github.com/codecov/engineering-team/issues/2296
This adds a new function which finds all the "stale" `plan_activated_users` for a set of given `orgs`. Users are considered stale if they don’t have any recent auth session or pull request. Those users will then be removed from the `plan_activated_users`.
> Add an admin action to remove stale `plan_activated_users`

- codecov/settings_base.py
- graphql_api/types/query/query.py
- requirements.in
- requirements.txt
- utils/logging_configuration.py
The 2.x line of releases includes new features like support for the queue module.
Also, we've been seeing some disconnected spans in https://github.com/getsentry/sentry-python/issues/3169. Since there's a new major version of the SDK that includes significant changes, we first want to check whether the issue still exists in this new major version.
- https://github.com/getsentry/sentry-python/issues/3169
- Bumps `sentry-sdk` to `2.13.0`.
- Migrates `1.x` SDK API to `2.x`. (See also [migration guide](https://docs.sentry.io/platforms/python/migration/1.x-to-2.x).)
> build(deps): Bump sentry-sdk to 2.13.0

- core/commands/pull/interactors/fetch_pull_request.py
- core/commands/pull/interactors/tests/test_fetch_pull_request.py
Closes these sentry issues: https://codecov.sentry.io/issues/?environment=production&environment=dd&environment=enova&environment=epic&environment=roblox&environment=snowflake&project=5514400&project=5215654&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+unsupported+operand+type%28s%29&referrer=issue-list&statsPeriod=7d
When a user doesn't have an updatedstamp on their pull being compared, we just error the page, leading to a bad experience for the users. This PR just adds a guard when that's the case so we return "false"
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as …
> fix: Add guard when no update timestamp on pull

- webhook_handlers/views/github.py
This PR aims to gracefully handle a couple github webhook errors I saw in sentry
https://codecov.sentry.io/issues/2975145852
https://codecov.sentry.io/issues/4394424045
In both cases I just defaulted the get to a string so they wouldn't fail and would make it to the lines of code that exit the function early. I don't think this will have any meaningful impact, but it was a quick fix I saw so might as well
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all …
> fix: Small fixes for some unhandled github webhook errors

- .github/workflows/ci.yml
- .github/workflows/pr_detect_shared_changes.yml
https://github.com/codecov/gha-workflows/pull/32 will change this to use `main` before merging
- [run that skips posting a comment because shared was not changed](https://github.com/codecov/codecov-api/actions/runs/10726429651/job/29746451116?pr=801)
- [run that posts a comment to this PR](https://github.com/codecov/codecov-api/actions/runs/10726447902/job/29746511187?pr=801)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that …
> move shared change check to separate workflow with correct permissions

- codecov_auth/middleware.py
- codecov_auth/tests/unit/test_authentication.py
- graphql_api/actions/repository.py
- graphql_api/tests/helper.py
- graphql_api/tests/test_current_user_ariadne.py
- graphql_api/tests/test_owner.py
- graphql_api/types/me/me.py
- graphql_api/types/owner/owner.py
https://github.com/codecov/internal-issues/issues/711
> Show Okta Enforced Repos when Impersonating

- codecov/tests/test_urls.py
- codecov/urls.py
- codecov/views.py
- graphs/helpers/badge.py
- graphs/views.py
This PR aims to fix a security backdoor where users can abuse the open redirect for codecov to potentially lead a user to a malicious website.
This was patched 3 years ago and [moved to being done at the ingress level](https://github.com/codecov/k8s-v2/commit/95bd8b323c18dc6d870d277e16d6aa675f071b2c) but the underlying code was never removed. We're just looking to remove the code now
Closes https://github.com/codecov/internal-issues/issues/653
I may take a stab at also doing some sanitization of the SVGs too but this will at least close the issue
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov …
> sec: remove open redirect to codecov

- graphql_api/tests/test_repository.py
- graphql_api/types/repository_config/repository_config.graphql
- graphql_api/types/repository_config/repository_config.py
Fixes these sentry issues: 
https://codecov.sentry.io/issues/5416346385
https://codecov.sentry.io/issues/5416346358
I can't really tell why we would only want indication range to be an integer, we should also accept float values too for individuals who want a finer level of precision. My understanding is something else (either client or different server code) bounds the range to be between 0 and 100 so this shouldn't affect anything really.
This PR just swaps the type from an int to a float in GQL and changes the python types to match
Closes https://github.com/codecov/engineering-team/issues/2475
**Gazebo might be slightly updated now:**
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity …
> fix: Indication range from int -> float

- graphql_api/views.py
Just adding a couple logs around the GQL rate limiter to better find the keys being used
> dev: Add a couple logs around gql rate limiter

- graphql_api/types/comparison/comparison.py
- graphql_api/types/impacted_file/impacted_file.py
- services/comparison.py
Debug why get impacted files segments and comparison hasDifferentNumberOfHeadAndBaseReports are slow. To be reverted once debugging is done.
> debug: add log and trace for impacted file

- graphql_api/actions/measurements.py
- services/bundle_analysis.py
use the owner_id index when querying the timeseries_measurement table
> bundle analysis: fix slow trend query

- rollouts/__init__.py
- upload/serializers.py
- upload/tests/views/test_reports.py
- upload/views/reports.py
Originally I wanted to delete PreProcess task completely, but after reviewing
certain usage patterns I realized the task is necessary (for `empty-upload` and
`static-analysis` for example).
So the alternative is to reduce the amount of times it is called, to only be called
when we effectively create a new report. Similar to https://github.com/codecov/codecov-api/pull/804
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some …
> chore: reduce usage of PreProcess task

- codecov_auth/tests/unit/views/test_okta_cloud.py
- codecov_auth/views/okta_cloud.py
We need a way to tell frontend that it's erroring, this is redirecting to the dashboard with an error param that will be caught in gazebo. 
[Improve Okta Login Error Handling for users](https://github.com/codecov/engineering-team/issues/2347)
Check for error in the callback -> redirect to app wit the error and err description sent via OKTA 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize …
> Redirect with an error param on okta callback

- services/yaml.py
> Add extra log debugging for unable to fetch_commit_yaml

- services/yaml.py
The call from this function is coming from a lot of places, while it's only expecting a `Owner` type there has been other types being passed in.
> Log all type of "owner" arg for fetch_commit_yaml

- api/public/v2/compare/views.py
- api/public/v2/component/views.py
- api/public/v2/report/views.py
- api/public/v2/tests/test_api_compare_viewset.py
- api/public/v2/tests/test_api_component_viewset.py
- api/public/v2/tests/test_report_viewset.py
- api/public/v2/tests/test_totals_viewset.py
- services/tests/test_yaml.py
- services/yaml.py
- upload/tests/views/test_empty_upload.py
- upload/views/empty_upload.py
- In empty-upload depending on the auth classes used, the `request.user` can be `Owner` or `RepositoryAsUser`, need to make sure when sending to `final_commit_yaml` it will be `Owner`
- Several places in public API, it passes in to `fetch_commit_yaml ` a `User` object of the authenticated request maker, which is wrong. Instead it should be the `Owner` of the requested organization
- Add an assertion to `fetch_commit_yaml` to make sure if an `owner` arg is passed in it is in fact `Owner`, previously this error is not surfaced because we just do a catch all exception.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from …
> Make sure calls to fetch_commit_yaml are Owner type

- api/internal/coverage/views.py
- api/internal/tests/views/test_coverage_viewset.py
the second arg of commit_components should be the Owner object of the commit/repo. Not the authenticated `User` object.
Fixes https://codecov.sentry.io/share/issue/46e6e17c75f34297a2e9d76a82598eef/
> fix CoverageViewSet where incorrect arg is passed to commit_components

- api/internal/tests/views/test_compare_viewset.py
- api/public/v2/tests/test_api_compare_viewset.py
- services/comparison.py
- services/tests/test_comparison.py
Following up from https://github.com/codecov/codecov-api/pull/780, remove unused code pertaining to the old YAML field. This closes https://github.com/orgs/codecov/projects/31/views/11?pane=issue&itemId=77144226.
> Remove coverage offsets related code

- timeseries/helpers.py
- timeseries/tests/test_helpers.py
This PR aims to fix these two Sentry issues:
https://codecov.sentry.io/issues/3984451805
https://codecov.sentry.io/issues/3984451718
where we're trying to resolve measurements on the repository object but there is a race condition that exists where calling create may result in a duplicate key value (race condition)
The fix was to change the create to a get_or_Create and add some conditional logic to only backfill if the function returns "true" for created
Closes https://github.com/codecov/engineering-team/issues/2525
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going …
> fix: Resolve race condition when resolving measurements

- api/public/v2/pull/views.py
- api/public/v2/test_results/views.py
- api/public/v2/tests/test_api_pull_viewset.py
- api/public/v2/tests/test_report_viewset.py
- api/public/v2/tests/test_test_results_view.py
- api/public/v2/tests/test_totals_viewset.py
This change unblocks some short term workflows between Codecov and Sentry's Seer service. Seer will query Codecov's pulls endpoint for a given PR and use coverage information to generate tests. 
> [temp] Add additional permissions to pulls and test results endpoint

- api/internal/owner/serializers.py
Logs out the phases leading to an error in owner serializer's get_scheduled_phases. To be used to assist in debugging a sentry issue I'm looking in to.
> debug: Add phases to error log in owner serializer's get_scheduled_phases

- api/internal/tests/views/test_account_viewset.py
- billing/tests/test_views.py
- billing/views.py
- plan/service.py
- services/billing.py
- services/tests/test_billing.py
We were eagerly updating the user's `plan` in the specific case where they already have a `subscription` and they are upgrading. We were updating without checking that the payment was successful, so in the case where we have updated the `plan` but the stripe payment fails, we were bumping the user all the way back to free tier.
https://github.com/codecov/engineering-team/issues/2407
stripe's docs: https://docs.stripe.com/billing/subscriptions/pending-updates
Only update the plan if the payment was successful. If it's not successful, reject the changes and give they user the delinquent pop-up. The user in our db and in Stripe's system stays on the original plan until they payment is successful.
> Fix stripe subscription upgrade failures

- billing/tests/test_views.py
- billing/views.py
This PR updates the Stripe webhook handlers to accept requests for subscriptions shared by multiple owners.
It seems previously we baked in the expectation that this could not occur, but it turns out there are cases where this is a valid state. Specifically, this was the old way we handled users with multiple orgs billed jointly. With the new Account model, we can handle this case for Enterprise cloud users, but there still exists non-enterprise cloud users who have joint billing setups which cannot be migrated to Account billing as they are not on enterprise cloud plans. Support has a spreadsheet containing some of these customers, but it seems there are more than listed there. 
Note that we do not need to handle this case for customer_subscription_created as that can only occur during …
> fix: Allow multiple owners per subscription in relevant stripe webhook handlers

- api/internal/owner/serializers.py
- billing/tests/test_views.py
Updates last instance of unsafely accessing a schedule/subscription's metadata. This was causing errors when the expected metadata doesn't exist.
Resolves https://codecov.sentry.io/issues/5332174795
> fix: Safely access schedule metadata to avoid error

- services/billing.py
- services/tests/test_billing.py
Stripe errors are popping up in logs with this message `StripeError raised: When `payment_behavior` is set to `pending_if_incomplete`, you can only pass supported params. `metadata` is not supported. See https://stripe.com/docs/billing/subscriptions/pending-updates-reference#supported-attributes for more details.`
There are several conflicting params, I'll have to sort them out later, for now removing this param from the .modify() call should fix the problem
https://github.com/codecov/engineering-team/issues/2407
https://docs.stripe.com/billing/subscriptions/pending-updates-reference
> remove payment_behavior - it's breaking subscription.modify

- api/public/v2/owner/serializers.py
- api/public/v2/owner/views.py
- api/public/v2/tests/test_api_owner_viewset.py
- api/public/v2/urls.py
- api/shared/owner/mixins.py
ref: https://github.com/codecov/internal-issues/issues/723
Add a new public V2 API endpoint to return list of users' login session status:
GET https://api.codecov.io/api/v2/{service}/{owner_username}/user-sessions?page={page}&page_size={page_size}
> Returns a paginated list of users' login session for the specified owner (org)
Note: Only callable if user is an admin of the org.
Params:
```
service (string): [required] Git hosting service provider
owner_username (string): [required] username from service provider
page (integer): A page number within the paginated result set.
page_size (integer): Number of results to return per page.
```
Response:
```
{
count: integer,
next: uri, 
previous: uri,
results: [{
name: string,
username: string,
has_active_session: boolean,
expiry_date: date-time …
```
> feat: Add public API endpoint to fetch user sessions

- codecov_auth/views/okta_cloud.py
Okta redirect wasn't working when users signed in through Sentry (instead of their git provider).
https://github.com/codecov/engineering-team/issues/2349
Changes the way we check whether the user is logged in.
> update okta cloud views

- graphql_api/tests/test_repository.py
- graphql_api/tests/test_test_result.py
- graphql_api/types/enums/enums.py
- graphql_api/types/enums/test_results_ordering_parameter.graphql
- graphql_api/types/test_results/test_results.graphql
- graphql_api/types/test_results/test_results.py
- reports/tests/factories.py
- utils/test_results.py
This PR does 2 things:
- add the lastDuration field to the TestResult GQL model
- use the DailyTestRollup object to query for aggregates, this is being done for perf reasons
depends on: https://github.com/codecov/worker/pull/699
> Improve aggregate test results function

- graphql_api/tests/test_repository.py
- graphql_api/tests/test_test_results_headers.py
- graphql_api/types/__init__.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
- graphql_api/types/test_results/__init__.py
- graphql_api/types/test_results/test_results.py
- graphql_api/types/test_results_headers/__init__.py
- graphql_api/types/test_results_headers/test_results_headers.graphql
- graphql_api/types/test_results_headers/test_results_headers.py
- utils/test_results.py
- TestResultsHeaders represents the information displayed in the Test
Analytics UI that is related to test results, total duration of tests,
accumulated duration of the 5% slowest tests, total number of failures,
and total number of skips
- a field of type TestResultsHeaders was added to the Repository model
depends on: https://github.com/codecov/codecov-api/pull/813
> add TestResultsHeaders GQL model

- graphql_api/tests/test_flake_aggregates.py
- graphql_api/tests/test_repository.py
- graphql_api/types/__init__.py
- graphql_api/types/enums/enums.py
- graphql_api/types/enums/test_results_ordering_parameter.graphql
- graphql_api/types/flake_aggregates/__init__.py
- graphql_api/types/flake_aggregates/flake_aggregates.graphql
- graphql_api/types/flake_aggregates/flake_aggregates.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
- graphql_api/types/test_results/test_results.graphql
- graphql_api/types/test_results/test_results.py
- graphql_api/types/test_results_aggregates/__init__.py
- graphql_api/types/test_results_aggregates/test_results_aggregates.graphql
- graphql_api/types/test_results_aggregates/test_results_aggregates.py
- graphql_api/types/test_results_headers/__init__.py
- utils/test_results.py
This contains the flakeCount and flakeRate fields. 
The flakeCount is calculated by getting all flakes that are active or ended in the last 30 days
The flakeRate is calculated by accumulating the flaky_fail_count / (pass_count + fail_count) for all tests
depends on: https://github.com/codecov/shared/pull/356 and https://github.com/codecov/codecov-api/pull/816
> Create the FlakeAggregates GQL model

- graphql_api/types/account/account.graphql
Converts type of Account's totalSeatCount Int! instead of Int.
> fix: Make Int non-nullable in totalSeatCount on Account

- graphql_api/tests/test_flake_aggregates.py
- graphql_api/tests/test_repository.py
- graphql_api/tests/test_test_results_headers.py
- graphql_api/types/flake_aggregates/flake_aggregates.graphql
- graphql_api/types/flake_aggregates/flake_aggregates.py
- graphql_api/types/repository/repository.py
- graphql_api/types/test_results/test_results.graphql
- graphql_api/types/test_results/test_results.py
- graphql_api/types/test_results_aggregates/test_results_aggregates.graphql
- graphql_api/types/test_results_aggregates/test_results_aggregates.py
- utils/test_results.py
This adds PercentChange fields to both the TestResultsAggregates
and the FlakeAggregates. These work by getting the aggregates
for the previous historical period and comparing them with the
ones for the current historical period and getting a percentage difference.
> add percent changes to test results and flakes aggregates

- graphql_api/tests/test_repository.py
- graphql_api/tests/test_test_result.py
- graphql_api/types/inputs/test_results_filters.graphql
- graphql_api/types/repository/repository.py
- reports/tests/factories.py
- utils/test_results.py
we want to be able to filter test results by a list of flags and by a
list of testsuite names so this adds that functionality.
this is done by adding testsuites and flags fields to the
TestResultsFilteringParameter GQL model
to filter by flags this uses the TestFlagBridge database model
> feat: add filtering for flags and testsuites

- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.graphql
- graphql_api/types/owner/owner.py
Adds activatedUserCount resolver on the Owner type. One small step towards removing the account details rest endpoint lol.
Closes https://github.com/codecov/engineering-team/issues/2555
> feat: Add activatedUserCount resolver to Owner

- graphql_api/views.py
https://redis.io/docs/latest/commands/setex/
Setex looks to be deprecated in favor of set, thanks @nora-codecov for letting me know! This PR just updates the GQL rate limit code from setex to set and defines the function params explicitly …
> ref: Replace setex with set in gql rate limit code

- webhook_handlers/views/github.py
Testing signature validation on forwarding webhook requests from AI reviewer. We want to ensure we log the same headers. 
> [temp] Add logs to incoming github webhook events 

- graphql_api/tests/test_account.py
- graphql_api/types/account/__init__.py
- graphql_api/types/account/account.graphql
- graphql_api/types/account/account.py
- graphql_api/types/config/__init__.py
- graphql_api/types/enums/account_organization_ordering.graphql
- graphql_api/types/enums/enum_types.py
- graphql_api/types/enums/enums.py
- graphql_api/types/okta_config/__init__.py
Adds the paginated organizations array resolver on the Account type in the graphql API.
Closes https://github.com/codecov/engineering-team/issues/2558
> feat: Add organizations array resolver on Account type

- graphql_api/tests/test_test_analytics.py
- graphql_api/tests/test_test_result.py
- graphql_api/tests/test_test_results_headers.py
- graphql_api/types/test_analytics/test_analytics.graphql
- graphql_api/types/test_analytics/test_analytics.py
Chatted with @ajay-sentry  - Rename fields in the new testAnalytics type introduced in this [PR](https://github.com/codecov/codecov-api/pull/852) to be more explicit
Before
```graphql
{
testAnalytics {
results
resultsAggregates
}
}
```
After
```graphql
{
testAnalytics {
testResults
testResultsAggregates
}
}
```
No frontend clients are hooked up to any of this yet so okay to make breaking change here
> fix: Rename graphql testResults

- graphql_api/tests/test_flake_aggregates.py
- graphql_api/tests/test_test_analytics.py
- graphql_api/types/inputs/test_results_filters.graphql
- graphql_api/types/repository/repository.py
- graphql_api/types/test_analytics/test_analytics.graphql
- graphql_api/types/test_analytics/test_analytics.py
- utils/test_results.py
Ported changes from https://github.com/codecov/codecov-api/pull/857 with merge conflicts resolved
> feat: add history, fix percent_diff rounding and flake aggregate time

- webhook_handlers/views/github.py
Not needed for debugging anymore. Revert https://github.com/codecov/codecov-api/pull/864
> Remove unused logs in github webhook controller

- graphql_api/types/test_analytics/test_analytics.graphql
Test Results Aggregates was missing history param but is needed for filtering on Gazebo
We can see its already on the resolver here: https://github.com/codecov/codecov-api/blob/f4a178c73f3e679feecc0a0315008472915d7fe0/graphql_api/types/test_analytics/test_analytics.py#L71
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, …
> fix: Add history to TestResultsAggregates key

- graphql_api/tests/test_test_analytics.py
- graphql_api/tests/test_test_result.py
- graphql_api/types/inputs/test_results_filters.graphql
- graphql_api/types/test_analytics/test_analytics.py
- graphql_api/types/test_results/test_results.graphql
- graphql_api/types/test_results/test_results.py
- graphql_api/types/test_results_aggregates/test_results_aggregates.graphql
- utils/test_results.py
- add total fail, skip and pass counts to the TestResult GQL model
- add total slow test number to test results aggregates
- allow filtering test results by name using a search term
> Add more fields for Test Analytics

- .github/workflows/ci.yml
> updating gha

- graphql_api/tests/test_test_result.py
- graphql_api/types/test_results/test_results.py
- reports/tests/factories.py
- utils/test_results.py
if a test has a computed name we want to return that as the test name in the GQL Test Result object instead of its uncomputed name otherwise just return its uncomputed name with the special separation character escaped
> feat: add use of computed_name in API

- graphql_api/tests/test_test_results_headers.py
- graphql_api/types/test_results_aggregates/test_results_aggregates.py
This PR aims to add resolvers for total_slowest_tests and similar percent change so we can link them up to the failed tests table
Also added related UT
> feat: Add total slowest test + percent change resolvers in API

- api/public/v2/owner/views.py
- graphql_api/tests/test_bundle_analysis_measurements.py
- graphql_api/tests/test_bundle_analysis_measurements_legacy.py
- graphql_api/types/bundle_analysis/base.graphql
- graphql_api/types/bundle_analysis/base.py
- services/bundle_analysis.py
Computes the trends measurements for asset types with unknown types, do this buy subtracting all the known bundle type sizes from the total bundle size for each time interval of the measurements data.
> bundle analysis: compute measurements for unknown asset types

- upload/tests/views/test_bundle_analysis.py
- upload/views/bundle_analysis.py
Shelter will pass the storage_path variable that it creates on its end. We want to acknowledge if a request comes from shelter, and if so use it's storage_path
> Add logic for BA endpoint to accept storage_path

- codecov/settings_base.py
- codecov/settings_staging.py
- graphql_api/tests/test_views.py
- graphql_api/views.py
This PR aims to move the hard coded gql rate limit value to an env variable that can be set per environment
In the same PR I've updated the staging limit to be 1000 from 300
> feat: Use env var for GQL rate limit instead of hard code val

- graphql_api/helpers/mutation.py
- graphql_api/tests/test_account.py
- graphql_api/tests/test_owner.py
- graphql_api/types/account/account.graphql
- graphql_api/types/account/account.py
- graphql_api/types/enums/account_organization_ordering.graphql
- graphql_api/types/enums/enum_types.py
- graphql_api/types/enums/enums.py
- graphql_api/types/owner/owner.py
Removes the ordering argument on the account organizations list because it turns out that the paginator can't handle/isn't intended to do sorting by count of a field. Was throwing errors.
Additionally, adds a new resolver decorator to allow users of an account to see the activatedUserCount of orgs in that same account. This was a necessary change to support the desired UI, otherwise we'd only show activated user counts for orgs that the user is a member of.
> fix: Remove ordering on account organizations list

- webhook_handlers/tests/test_github.py
- webhook_handlers/tests/test_github_enterprise.py
- webhook_handlers/views/github.py
a tangent off of the investigation in https://github.com/codecov/internal-issues/issues/928
> webhooks: force sync when user is removed from org

- graphql_api/tests/test_test_analytics.py
- graphql_api/tests/test_test_result.py
- graphql_api/types/inputs/test_results_filters.graphql
- graphql_api/types/test_analytics/test_analytics.graphql
- graphql_api/types/test_analytics/test_analytics.py
- graphql_api/types/test_results/test_results.py
- utils/test_results.py
- utils/tests/unit/test_cursor.py
- utils/tests/unit/test_search_base_query.py
this commit replaces the previous django orm code with an invocation
to do a raw sql query that performs much better for repos with a large
amount of data.
one worry with this approach is the risk for sql injection
in this specific case, we're passing most of the dynamic user provided
values used in the sql through the parameters which the django docs say
are sanitized and should be used to protect against sql injection
for the user provided values that are not passed through the sql parameters
they're checked to be in a strict set of values, so we shouldn't be substituting
any unexpected strings into the query
> perf: Fix TestResults SQL query to not take as long

- graphql_api/tests/test_flake_aggregates.py
- graphql_api/tests/test_test_analytics.py
- graphql_api/tests/test_test_results_headers.py
- utils/test_results.py
we want to include the last day of the interval when we fetch test results and calculate aggregates.
we also want to remove the interval
date from the calculation of the percent changes.
> fix: make test analytics GQL queries use gte

- reports/tests/factories.py
there is a shared change that will remove the commits_where_fail
field from the Test model so having the commits_where_fail field
be set in the TestFactory will cause tests to fail
> test: fix TestFactory

- api/shared/repo/repository_accessors.py
- graphql_api/actions/repository.py
- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
- graphql_api/types/coverage_analytics/coverage_analytics.py
- graphql_api/types/impacted_file/impacted_file.py
- graphql_api/types/pull/pull.py
- services/bundle_analysis.py
- timeseries/helpers.py
Preemptively add Sentry traces at likely/possible chokepoints so that when we have an issue to debug why things are slow it would increase the chances that we already have traces for it.
> Add generous amounts of tracing throughout the repo

- labelanalysis/serializers.py
- requirements.in
- requirements.txt
- staticanalysis/serializers.py
- upload/tests/test_upload.py
- upload/tests/views/test_uploads.py
- upload/views/legacy.py
- upload/views/uploads.py
- webhook_handlers/tests/test_github.py
- webhook_handlers/views/github.py
`shared.metrics` does not re-export `statsd` anymore.
> Update `shared` and remove statsd metrics usage

- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
- graphql_api/types/impacted_file/impacted_file.py
- graphql_api/types/line_comparison/line_comparison.py
- graphql_api/types/me/me.py
- graphql_api/types/mutation/delete_component_measurements/delete_component_measurements.py
- graphql_api/types/mutation/delete_flag/delete_flag.py
- graphql_api/types/mutation/onboard_user/onboard_user.py
- graphql_api/types/mutation/regenerate_repository_token/regenerate_repository_token.py
- graphql_api/types/mutation/save_okta_config/save_okta_config.py
- graphql_api/types/owner/owner.py
- graphql_api/types/plan/plan.py
- graphql_api/types/plan_representation/plan_representation.py
- graphql_api/types/repository/repository.py
This other [PR](https://github.com/codecov/codecov-api/pull/610) deprecated the snake case fallback resolver in favor of ariadne's `convert_names_case` option. 
> The default object case behavior is deprecated: [snake case fallback resolver](https://ariadnegraphql.org/docs/api-reference#snake_case_fallback_resolvers)
Ariadne calls out [convert_names_case](https://ariadnegraphql.org/docs/api-reference#make_executable_schema) as the new correct way to convert case names
This PR is a follow-up clean-up to remove the since-duplicated instances of the snake case decorator.
Tested by smoke testing on staging and confirming no regression in these graphql queries
Closes https://github.com/codecov/engineering-team/issues/1879
Closes https://github.com/codecov/engineering-team/issues/2757 …
> chore: Dedupe kwargs snake case decorator

- graphql_api/types/owner/owner.py
- graphql_api/types/repository/repository.py
Fixes https://codecov.sentry.io/issues/6025778920/?notification_uuid=ecce812e-6bac-4e0d-b535-a01910b79bc2&project=5215654&referrer=assigned_activity-email
> Fix anon user case for upload tokens

- requirements.in
- requirements.txt
This PR bumps our django version from 4.2.15 -> 4.2.16.[ Changlog here](https://docs.djangoproject.com/en/5.1/releases/4.2.16/)
No breaking changes with this update.
Closes https://github.com/codecov/internal-issues/issues/906
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under …
> chore: Bump Django version to 4.2.16

- codecov/settings_base.py
Closes https://github.com/codecov/internal-issues/issues/916
Turning the setting off for `SettingsModule.PRODUCTION.value` and `SettingsModule.ENTERPRISE.value`
Tested locally by setting the line to `get_settings_module() != SettingsModule.DEV.value` and tried accessing at http://localhost:8000/graphql/ and the page was inaccessible.
> chore: Remove GQL playground access from prod

- services/billing.py
- services/tests/samples/stripe_invoice.json
- services/tests/test_billing.py
Adding auto-refund logic for when a user cancels their subscription within 24 hours (monthly charge) or 72 hours (yearly charge) of the period starting and being charged.
Open to any and all feedback including styling and syntax recommendations as this is one of my first python/codecov-api PRs. Should I wrap Stripe API calls in a try/catch?
Closes https://github.com/codecov/engineering-team/issues/2508
- Follows ideas at https://github.com/codecov/engineering-team/issues/1813#issuecomment-2290200974
- Follows https://docs.stripe.com/billing/subscriptions/cancel with https://docs.stripe.com/api/subscriptions/cancel
- Last line of https://docs.stripe.com/billing/subscriptions/cancel#prorate-for-usage-based-billing
- To [refund your …
> Stripe Auto-refund cancellation within Grace Period

- core/management/commands/delete_rate_limit_keys.py
- core/tests/test_management_commands.py
This PR adds a new django command to be run on CRON clearing any lingering users who may have had a redis key for their rate limit failing to expire.
The command runs only on user's (non-anon) by default, but an option can be passed in to run the deletion on anon users instead as well. We utilize the scan_iter function on redis because it's capable of having a regex path passed in, from which we go through and delete each of the keys. We only delete keys which have no TTL (comes back as -1 when you call the ttl function)
Redis Scan Docs - https://redis.io/docs/latest/commands/scan/
Redis TTL Docs - https://redis.io/docs/latest/commands/ttl/
Closes [#2527](https://github.com/codecov/engineering-team/issues/2527)
Will need the second half to be completed by …
> feat: Create Django Command for Deleting Rate Limit Redis Keys

- codecov/settings_test.py
- codecov_auth/signals.py
- codecov_auth/tests/test_signals.py
- core/signals.py
- core/tests/test_signals.py
- pytest.ini
- requirements.in
- requirements.txt
- utils/shelter.py
`Shelter` needs to know some things about `Owner`.
https://github.com/codecov/engineering-team/issues/2299
Goes with this piece https://github.com/codecov/shelter/pull/203
Depends on https://github.com/codecov/shared/pull/411
This new signal will trigger `Shelter` to pick up the object and store the relevant fields.
> add signal for Owner

- graphql_api/actions/commits.py
- graphql_api/dataloader/commit.py
- services/comparison.py
- services/tests/test_comparison.py
This removes all usage of `ReportDetails`. The base definitions still exist.
> Remove usage of `ReportDetails`/`files_array`

- Makefile
- upload/helpers.py
- upload/tests/test_upload.py
Removing commit update for consistency. This is not done in the new upload endpoint. The upload process takes care of this. …
> Removing commit update for consistency

- requirements.in
- requirements.txt
Bumps shared to latest commit
Includes https://github.com/codecov/shared/commit/cc72dcbaab563259257865ae993c8d48b393ccf7
> feat: Bump Shared to latest

- codecov/settings_base.py
- utils/logging_configuration.py
For security, we need to add in RFC3339 timestamps to API logs
https://github.com/codecov/infrastructure-team/issues/388
> fix: add UTC time to API logs

- billing/tests/test_views.py
- billing/views.py
- services/task/task.py
This PR adds code to send emails (through the send email worker task) to all owner admins when an invoice payment fails. We are doing this because the current stripe behavior only sends the notification email to the address associated with the stripe customer.
Depends on https://github.com/codecov/worker/pull/835
Closes https://github.com/codecov/engineering-team/issues/2483
Closes https://github.com/codecov/engineering-team/issues/2484
Closes https://github.com/codecov/engineering-team/issues/2485
> feat: Send email to admins on failed payment

- billing/tests/test_views.py
- billing/views.py
Fixes weird bug in subscription creation webhook flow that caused customer's default payment method to not be set.
> fix: Race condition in subscription creation webhook handlers

- graphql_api/tests/test_views.py
- graphql_api/views.py
https://github.com/codecov/internal-issues/issues/915
> fix: Don't show detailed errors for anonymous users

- upload/helpers.py
- upload/tests/test_helpers.py
- upload/tests/views/test_commits.py
- upload/tests/views/test_reports.py
- upload/tests/views/test_uploads.py
This link has pointed to the wrong place ever since we moved from the settings page to the configuration page. This PR adjusts that.
Ticket: https://github.com/codecov/engineering-team/issues/2841
> adjust deactivated repo url

- upload/views/empty_upload.py
- upload/views/test_results.py
- upload/views/upload_completion.py
https://github.com/codecov/engineering-team/issues/2300
Auth stack on upload endpoints needs to match what's on `shelter`, which treats all upload endpoints equally.
> add true tokenless to all upload endpoints, remove from TR

- .github/workflows/ci.yml
We want to add `basic-test-results` to our CI workflow for dogfodding.
Update test workflow to also use the `basic-test-results` action.
The change to add the action to the shared actions is: https://github.com/codecov/gha-workflows/pull/34
This will add another message spam to our PRs. …
> Update workflow to use basic-test-results

- services/billing.py
- services/tests/test_billing.py
Parameters should not include `created.` as it is inside of the `created` dictionary.
https://dashboard.stripe.com/logs?showIP=false&created%5Bgte%5D=1730707200&created%5Blte%5D=1730793599&method%5B0%5D=get&method%5B1%5D=delete&path=%2Fv1%2Finvoices&direction%5B0%5D=self&direction%5B1%5D=connect_in&starting_after=1730793070-req_kZrihx2qSFEA9u
> fix: Fix stripe invoice time bounding param names

- codecov/settings_base.py
- codecov/settings_staging.py
- utils/test_results.py
Closes Sentry error https://codecov.sentry.io/issues/6058399091/?environment=staging&project=5215654&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=5 related to access denied issue on staging when trying to fetch test results
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that …
> fix: Update GCS bucket name for staging

- graphql_api/types/test_analytics/test_analytics.py
not returning has_next_page or has_previous_page is causing a GQL error
> fix: has_{next,previous}_page are not nullable

- utils/test_results.py
previously we were returning a table that had a bunch of null columns
this is actually due to us not having a strict schema on the worker side
but a good fix here anyways is to return None from get_results when
there's no data in the table
> fix: get_results returns none if table is empty

- codecov_auth/tests/test_admin.py
- plan/service.py
- plan/tests/test_plan.py
This is a temporary PR to remove the requirement to start trials on a paid org to easily capture customers in paid plans we want to offer TA features to.
> Temporarily disable trials starting for paid orgs

- graphql_api/types/test_analytics/test_analytics.py
Fixes https://codecov.sentry.io/issues/6059519163/?project=5215654&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=4
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> fix: Default for test suites and flags

- graphql_api/tests/test_owner.py
- requirements.in
- requirements.txt
- upload/tests/views/test_bundle_analysis.py
- upload/tests/views/test_commits.py
- upload/tests/views/test_reports.py
- upload/tests/views/test_uploads.py
when true tokenless goes live we will merge this, which will make true tokenless default to "on" for new orgs.
https://github.com/codecov/engineering-team/issues/2623
> flip default value on upload_token_required_for_public_repos

- upload/tests/views/test_upload_coverage.py
- upload/urls.py
- upload/views/upload_coverage.py
After some discussion it seems `combined-upload` should be renamed to `upload-coverage`. …
> Change combined-upload to upload-coverage for clarity

- upload/tests/views/test_upload_coverage.py
- upload/views/upload_coverage.py
> Use consistent variable naming in upload coverage API requests

- graphql_api/tests/test_views.py
- graphql_api/validation.py
- graphql_api/views.py
When a GQL request is made with variables in the query but doesn't have the matching variable name provided in the request we get an internal server error. This handles a few hundred times a day, presumably for some reason the FE request is malformed, this leads to a lot of Sentry errors being spammed as well.
fixes: https://github.com/codecov/internal-issues/issues/959
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry …
> GQL: Handle internal server error from missing variables

- graphql_api/tests/test_commit.py
- graphql_api/types/bundle_analysis/base.graphql
- graphql_api/types/bundle_analysis/base.py
Set up the GQL field for returning routes of a given asset. Currently just hardcode some return value so that FE can start using it for testing. Coming up next PR will be calculating the real values
> Bundle analysis: Temp mock for routes field of Assets

- requirements.in
- requirements.txt
This is to test out the uv changes
> Upgrade shared to latest

- graphql_api/tests/test_repository.py
- graphql_api/types/owner/owner.py
- services/activation.py
We used to auto-activate only if both coverage and bundle were enabled. This fix ensures that if one product is enabled, auto-activation still works as expected.
We don't need OwnerNotActivatedError anymore, this is handled by isCurrentUserActivated in gazebo 
Fixes: [[Self-hosted] Auto-activate members doesn't work in latest/24.10.1](https://github.com/codecov/feedback/issues/554)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and …
> fix: Fix auto activation in the repo level 

- graphql_api/types/query/query.py
We must check for user in the request, current owner might not always be set for enterprise. 
[[Self-hosted] UnauthorizedGuestAccess error after updating from 24.8.1 to 24.9.3/24.10.1/24.11.1](https://github.com/codecov/feedback/issues/536)
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …
> fix: Check if user exists in info context before raising Guest Access error 

- codecov_auth/authentication/helpers.py
The new endpoint `upload/<service>/<slug>/upload-coverage` does not follow the regex `upload/<service>/<slug>/commits/...`, which is used in for example:
- `upload/<service>/<slug>/commits/<commit-sha>`
- `upload/<service>/<slug>/commits/<commit-sha>/report/<report-code>`
- `upload/<service>/<slug>/commits/<commit-sha>/report/<report-code>/upload`)
and this fix adds `upload-coverage` to the regex to correct auth behaviour for the new endpoint.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result …
> Add upload-coverage to regex for Auth

- graphql_api/tests/test_commit.py
- graphql_api/types/__init__.py
- graphql_api/types/bundle_analysis/__init__.py
- graphql_api/types/bundle_analysis/base.graphql
- graphql_api/types/bundle_analysis/base.py
- services/bundle_analysis.py
closes: https://github.com/codecov/engineering-team/issues/2941
Add bundle report info to GQL `BundleReport.info: BundleInfo`
```
type BundleInfo {
version: String!
plugin_name: String!
plugin_version: String!
built_at: String!
duration: Int!
bundler_name: String!
bundler_version: String!
}
``` …
> Bundle Analysis: expose bundle report info to GQL

- billing/helpers.py
- billing/views.py
- services/task/task.py
This PR re-enables failed payment emails after fixing the template. Also pulls out the logic for fetching admins from owners to a helper function for easier reuse.
> feat: Re-enable failed payment emails

- billing/tests/test_views.py
- billing/views.py
This PR adds the logic for sending the new success-after-failed-payment email template. It also addresses a bug where the card wasn't being properly populated on the other failed-payment email.
Closes https://github.com/codecov/engineering-team/issues/2503
Closes https://github.com/codecov/engineering-team/issues/3119
> feat: Add success after failed payment email (and fix card in failed-payment email)

- graphql_api/tests/test_owner.py
- graphql_api/tests/test_plan.py
- graphql_api/tests/test_plan_representation.py
- graphql_api/types/plan/plan.graphql
- graphql_api/types/plan/plan.py
- graphql_api/types/plan_representation/plan_representation.graphql
- graphql_api/types/plan_representation/plan_representation.py
This PR removes an unused field to help cleanup the plan types that we have and reduce some noise. If we plan on combining the types into one in the future this will make our life just a little bit easier.
Closes https://github.com/codecov/engineering-team/issues/3141
No references in gazebo that I could see, this looks safe to remove.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and …
> chore: Remove deprecated plan name field from plan and plan representation types

- api/internal/owner/serializers.py
- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.py
- graphql_api/types/plan_representation/plan_representation.graphql
- graphql_api/types/plan_representation/plan_representation.py
- requirements.in
- requirements.txt
Still need the update version of shared after merging this PR: https://github.com/codecov/gazebo/pull/3602  to pass the tests 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute …
> ref: Update shared + Add missing fields for plan representation 

- billing/views.py
- requirements.in
- requirements.txt
This PR bumps the stripe version from 9.6 -> 11.4.1 and changes the API version from 4/24 -> 12/24.
[Changelog](https://github.com/stripe/stripe-python/releases?page=1)
[Stripe Docs](https://docs.stripe.com/upgrades#2024-12-18.acacia)
Additional context on worker PR
Relates to https://github.com/codecov/worker/pull/981 …
> chore: Update Stripe and pin API to latest version

- api/internal/tests/views/test_self_hosted_user_viewset.py
- api/internal/tests/views/test_user_viewset.py
- codecov/tests/base_test.py
- services/tests/test_repo_providers.py
I was looking into ways to speed up our test suite and stumbled upon a comment on the "TestCase" class in Pytest where it mentioned it being quicker to execute than TransactionTestCase
I got to tinkering a bit and saw that with a simple drop in replacement of TestCase from TransactionTestCase we were able to reduce the runtime of our api/internal pathed test suites from ~38 seconds to under 15 🤯 The results honestly astonished me, and this might end up being a better way to tackle the speed problem prior to doing the parallelization effort, which seemed kinda tough due to needing to understand all our test fixtures anyway.
I may end up creating an investigation ticket at some point to try and migrate some more of these over, or hand off to someone else, but this seems really big! Even …
> dev: Swap Transaction Test case for Test Case in api/internal tests

- services/billing.py
Missed a reference for updating stripe version, oops
> fix: Missed a reference for updating API version

- api/internal/commit/serializers.py
- api/internal/tests/views/test_account_viewset.py
- codecov_auth/tests/test_admin.py
- codecov_auth/views/base.py
- core/signals.py
- graphql_api/dataloader/comparison.py
- graphql_api/tests/test_owner_measurements.py
- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/plan_representation/plan_representation.py
- ruff.toml
- services/bundle_analysis.py
- services/profiling.py
- timeseries/helpers.py
- upload/tests/views/test_upload_coverage.py
- upload/tests/views/test_uploads.py
- upload/views/empty_upload.py
- webhook_handlers/views/github.py
Was looking through the ruff rules list and saw these comprehension style rules which I kinda liked. They all had unsafe-auto fixes available but I was able to go through each one and do a manual replace for all of them
If we like it we can do a similar exercise for Shared / Worker, I think the notation is a lot clearer for me but maybe folks think otherwise and we should scrap this idea.
Closes https://github.com/codecov/engineering-team/issues/3151
Rule fixes were:
[C401](https://docs.astral.sh/ruff/rules/unnecessary-generator-set/)
[C403](https://docs.astral.sh/ruff/rules/unnecessary-list-comprehension-set/)
[C405](https://docs.astral.sh/ruff/rules/unnecessary-literal-set/)
[C416](https://docs.astral.sh/ruff/rules/unnecessary-comprehension/) …
> dev: Add Ruff C4 rules

- enterprise.sh
- graphql_api/tests/test_owner.py
- graphql_api/types/query/query.py
- prod.sh
- staging.sh
> Gunicorn conf

- graphql_api/tests/test_plan.py
- graphql_api/types/plan/plan.py
Resolves the following error
```
None is not a valid TrialStatus\n\nGraphQL request:14:9\n13 | trialEndDate\n14 | trialStatus\n | ^\n15 | trialStartDate
...
File \"/app/graphql_api/types/plan/plan.py\", line 35, in resolve_trial_status\n return TrialStatus(plan_service.trial_status)\n
```
> [fix] Fix trial status resolver when status is None

- graphql_api/tests/test_impacted_file.py
- graphql_api/types/impacted_file/impacted_file.py
- services/comparison.py
- services/tests/test_comparison.py
Closes https://github.com/orgs/codecov/projects/31/views/11?pane=issue&itemId=88922866&issue=codecov%7Cengineering-team%7C3030
We choose segments with indirectly changed lines even if a user queries for intended changes only if they have diff changes. With this PR, we will exclude those lines from each segment.
> [fix] Only count directly changed lines as misses when intended changes is specified

- enterprise.sh
- prod.sh
- staging.sh
> Update gunicorn conf

- requirements.in
- requirements.txt
This update primarily pulls in a DB migration to add a better index (concurrently) to `Upload`/`ReportSession`.
> Update shared for `Upload` DB index

- api/internal/commit/serializers.py
- codecov_auth/commands/owner/interactors/save_terms_agreement.py
- codecov_auth/signals.py
- codecov_auth/views/sentry.py
- core/commands/commit/interactors/get_file_content.py
- graphql_api/actions/repository.py
- upload/serializers.py
- upload/tokenless/azure.py
- upload/views/uploads.py
- validate/views.py
> API Improvements: Fix typings for various files pt4

- graphql_api/tests/test_owner.py
- graphql_api/types/query/query.py
Follows up to https://github.com/codecov/codecov-api/pull/910 which added restrictions to Enterprise "guest_access: off" behavior.
This PR adds in a fix to account for when a user owner does not have any plan_activated_users. From what I could tell from our current data model this is not possible, but I think historic data ends up with this case which caused the reported issue by customer, so fixed with this PR.
> fix: Fix deactivated enterprise user when no plan activated users

- codecov/settings_base.py
- codecov/settings_enterprise.py
- utils/shelter.py
In self-hosted / enterprise, our customers may not always have shelter deployed. Only initialize the shelter PubSub client if shelter is enabled.
This fixes a bug where regenerateOrgUploadToken was failing when the token object was attempted to create but the corresponding signal failed.
I tested against local gazebo pointed to this with enterprise env vars that an org upload token was generated
Closes https://github.com/codecov/engineering-team/issues/3211
> fix: Handle disabled shelter

- requirements.in
- requirements.txt
This primarily pulls in https://github.com/codecov/shared/pull/442 to remove some unused indices from the production table, and align the migration state with the reality of the DB.
> Update `shared` to pull in migrations

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
Exposes repoid in our GraphQL repository schema. This is necessitated by incoming Amplitude integration in Gazebo.
> feat: Add repoid to repository graphql schema

- codecov_auth/commands/owner/interactors/get_is_current_user_an_admin.py
- core/management/commands/check_for_migration_conflicts.py
- core/management/commands/delete_rate_limit_keys.py
- core/management/commands/update_gitlab_webhooks.py
- graphql_api/tests/test_plan.py
- open_telemetry.py
- ruff.toml
This PR aims to add the ruff print rules to API, and either removes or ignores each print statement (I just used my best judgement)
Ruff rules can be found here: https://docs.astral.sh/ruff/rules/#flake8-print-t20
Closes https://github.com/codecov/engineering-team/issues/3279
> dev: Add Ruff print rules to API (T20)

- codecov/commands/base.py
- core/commands/component/interactors/delete_component_measurements.py
- core/commands/component/tests/test_component.py
- core/commands/flag/interactors/delete_flag.py
- core/commands/flag/tests/test_flag.py
- core/commands/repository/interactors/activate_measurements.py
- core/commands/repository/interactors/erase_repository.py
- core/commands/repository/interactors/regenerate_repository_token.py
- core/commands/repository/interactors/regenerate_repository_upload_token.py
- core/commands/repository/interactors/tests/test_erase_repository.py
- core/commands/repository/interactors/update_bundle_cache_config.py
- core/commands/repository/repository.py
- graphql_api/types/mutation/erase_repository/erase_repository.py
This changes the `EraseRepositoryInteractor` to allow erasing repositories belonging to other owners the `current_owner` has admin access to.
While doing so, this also extracts some duplicated code related to resolving `Owner`s and `Repository`s by name, and validating admin access.
The main part to allow this functionality (changing the GraphQL query) is left to a followup PR.
> Allow erasing a foreign Repo

- graphql_api/tests/test_billing.py
- graphql_api/types/__init__.py
- graphql_api/types/billing/__init__.py
- graphql_api/types/billing/billing.graphql
- graphql_api/types/billing/billing.py
- graphql_api/types/owner/owner.graphql
- graphql_api/types/owner/owner.py
- services/billing.py
- services/tests/test_billing.py
- utils/test_utils.py
Another piece of work for the ACH microdeposits delayed payment verification flow - https://github.com/codecov/engineering-team/issues/2622
This PR adds an endpoint to fetch from Stripe any payment methods awaiting delayed payment notification (e.g., ACH 2-day later microdeposits).
It hooks into our GraphQL api at a new `billing` key that we can extend and add to as we cut over stuff from the existing /internal/account-details REST api.
It will be used by gazebo UI to reflect this waiting status to the user in that 2-day period.
> feat: Add list unverified payment methods api

- upload/views/uploads.py
> feat: Improve upload storage path generation for reports

- graphql_api/tests/test_views.py
- graphql_api/views.py
fixes: https://github.com/codecov/internal-issues/issues/1211
We get internal server error when requests are made to GQL with an empty request body "{}", this fix catches that and returns a bad requests gracefully.
> fix: handle internal server error when no GQL request body received

- api/internal/owner/serializers.py
- services/billing.py
- services/tests/test_billing.py
Some more plan optimizations for the update_plan helper and when determining if we want to fire the sentry webhook when moving to a sentry plan. Consequently updates the tests.
The update_plan helper change is the main one, mostly just consolidating the 2 queries to a single one and passing the relevant params down that are needed
This should be merged into the remove reference PR before merging that one, but can also be done separately
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my …
> ref: Plan query optimizations

- webhook_handlers/views/github.py
it's handled here
https://github.com/codecov/codecov-api/blob/ca253c138ce000c16126f7b3693a7bbd90ce1086/webhook_handlers/views/github.py#L732-L737
> fix: stop double-counting unhandled_event in github webhook handler

- billing/tests/test_views.py
- billing/views.py
This PR aims to fix a Sentry issue that popped up after we launched ACH related to a customer trying to update their payment method while having multiple stripe subscription_ids tied to the customer_id in our DB. I noticed that for this customer both of the subscription_ids were the same, but wanted the code to accommodate cases where that wasn't necessarily the case; potentially someone who wants to spread Codecov across the many orgs their apart of ;) 
Closes https://github.com/codecov/engineering-team/issues/3323
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going …
> fix: Account for Multiple Owners being returned when handling stripe payment intent webhook

- codecov/settings_base.py
- codecov_auth/tests/unit/views/test_base.py
- codecov_auth/views/base.py
- webhook_handlers/tests/test_github.py
- webhook_handlers/views/github.py
Publishes Amplitude events for App Installed, User Created, and User Logged in.
Closes https://github.com/codecov/engineering-team/issues/3179
> feat: Publish onboarding events

- graphql_api/actions/path_contents.py
- graphql_api/tests/test_branch.py
- graphql_api/types/commit/commit.py
- services/path.py
- services/report.py
First of all, this fixes and adds missing type annotations.
It then deduplicates the code between `pathContents` and the `deprecated` variant, which were 99% identical.
Resolving the path contents was also optimized a little bit by not filtering the report for "files matching *any* session in the report", aka "all files". Other optimizations include avoiding some intermediate allocations by sorting lists in-place, and simplifying some functions.
> Refactor and optimize querying `pathContents`

- codecov/settings_base.py
> fix: Explicitly cast upload memory size config values to integers

- graphql_api/tests/mutation/test_erase_repository.py
- graphql_api/types/mutation/erase_repository/erase_repository.graphql
- graphql_api/types/mutation/erase_repository/erase_repository.py
Adding this as an optional input field, meaning it is backwards compatible, and falls back to the existing logic of using the currently logged in user as the target owner.
When specified, it will erase the repository belonging to the given `owner`.
> Add `owner` to `eraseRepository` mutation

- requirements.in
- requirements.txt
Updates shared from 3aea532 to 04b5f81
> chore: Update shared

- Makefile
needed for https://github.com/codecov/umbrella/pull/4
we bindmount our local `codecov-api` into the docker container. currently our local `codecov-api` is the actual git repo, so the `git` invocation works. in umbrella, it's not the actual git repo, so the command fails
apparently this is all i need to change...?
> makefile changes for monorepo prep

- graphql_api/tests/test_test_analytics.py
- graphql_api/types/test_analytics/test_analytics.py
instead of using startswith on the polars dataframe we want to filter by tests that contain the filtering term
> fix: TA GQL term filtering

- graphql_api/helpers/connection.py
- graphql_api/helpers/tests/test_connection.py
the CursorPaginator encodes `None` values as the string "None", and on decoding it interprets that as just another string which is causing bugs when running the SQL, because we'll be comparing random types against a string instead of against null
this fixes that by assigning a specific value (\x1f) that is unlikely to be in any user provided string that we would want to filter by
> fix: CusrorPaginator null encoding bug

- graphql_api/tests/test_owner.py
- graphql_api/types/owner/owner.graphql
- graphql_api/types/owner/owner.py
Giving access to two new owner properties regarding repos for use in this FE change https://github.com/codecov/engineering-team/issues/3074
- Adds `hasActiveRepos` and `hasPublicRepos` to the owner type
> feat: New properties for owner repos

- graphql_api/tests/test_branch.py
- services/path.py
Previously, the `ReportPaths.files` accessor would manually filter through the `unfiltered_report`. Even though the `self.report` was already filtered.
Now the custom filtering logic is a bit updated, but taking care of existing bugs in `FilteredReport`, as that is still yielding files even though they are not matching any `flags`.
In this profile, you can see calls to (unoptimized) `match`, once in `ReadonlyReport.filter`, and then again within `ReportPaths.files`.
> Do not double-filter Reports in `ReportPaths`

- graphql_api/types/path_contents/path_content.graphql
Makes PathContent's path attribute non-nullable. Was doing a TS conversion in Gazebo and noticed this was nullable, but upon checking the types in the resolver, path will always be defined.
> fix: Make PathContent's path non-nullable

- graphql_api/types/comparison/comparison.py
- services/comparison.py
- services/tests/test_comparison.py
This PR intends to improve loading times in the Pull detail page by adjusting the logic in the `has_different_number_of_head_and_base_reports` resolver.  
This is one of the many resolvers I'd like to tackle with the investigation done [here](https://www.notion.so/sentry/Coverage-Pulls-Tab-Cacheing-Project-19a8b10e4b5d80138e8ddf6a80b150a7).
This resolver calls the comparison.head_report, which always calls the `apply_diff` function, which ends up calling the provider. In some cases, this call is necessary, but for this particular resolver it is not as the logic inside the resolver compares number of sessions, not the contents of the sessions. Therefore, we're going to shave some time by adding a property that doesn't talk to the provider.
I left note in that implementation, there's an …
> Adjust call used in comparison file to avoid provider api call

- codecov_auth/admin.py
This change would cause impersonation to expire after 3 minutes.
> add max age to cookie

- Makefile
- docker-compose.yml
- docker/test.yml
- graphql_api/tests/test_config.py
Rather than messing with ENV in docker, this uses the test-global `config.yml` to enable timeseries tests, and switches to a lighter-weight timescale docker image.
> Enable timeseries tests, differently

- graphql_api/tests/test_branch.py
- graphql_api/tests/test_commit.py
- graphql_api/tests/test_repository.py
- graphql_api/types/file/file.graphql
- graphql_api/types/file/file.py
- graphql_api/types/path_contents/path_content.graphql
- graphql_api/types/path_contents/path_content.py
- graphql_api/types/repository/repository.graphql
- graphql_api/types/repository/repository.py
We're removing the deprecated impact analysis references now that these fields are no longer being queried for in API. Simple removal, in addition to removing the related references in the test suite
> ref: Remove isCriticalFile and profilingToken from GQL API

- services/tests/test_report.py
This field is private and should not be accessed directly. I’m about to remove it in the future.
> Remove usage of `_chunks` from tests

- .github/workflows/upload-overwatch.yml
> Integrate overwatch to CI

- codecov_auth/authentication/repo_auth.py
- upload/tests/views/test_test_results.py
- upload/views/test_results.py
- upload/views/uploads.py
previously it was broken because it was trying to get the repository and commit information from the request path, when TA requests store that information in the body. So we take the same modifications that the BA tokenless authentication made but change the service to be fetched from the "service" key instead of the "git_service" key
Fixes: https://github.com/codecov/codecov-action/issues/1762
> fix: TA tokenless uploads

- api/internal/tests/views/test_coverage_viewset.py
- api/public/v2/report/views.py
- api/public/v2/tests/test_api_compare_viewset.py
- api/public/v2/tests/test_api_component_viewset.py
- api/public/v2/tests/test_file_report_viewset.py
- api/public/v2/tests/test_flag_viewset.py
- api/public/v2/tests/test_report_tree.py
- api/public/v2/tests/test_report_viewset.py
- api/public/v2/tests/test_totals_viewset.py
- compare/commands/compare/interactors/fetch_impacted_files.py
- compare/commands/compare/interactors/tests/test_fetch_impacted_files.py
- conftest.py
- graphql_api/tests/test_branch.py
- graphql_api/tests/test_commit.py
- graphql_api/tests/test_components.py
- graphql_api/tests/test_impacted_file.py
- graphql_api/tests/test_path_content.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
- pyproject.toml
- services/components.py
- services/tests/test_components.py
- services/tests/test_path.py
- services/tests/test_report.py
- timeseries/tests/test_helpers.py
- uv.lock
We are using the `.flags` property in a lot of places where we only ever wanted the `.keys()`. So lets use `get_flag_names` instead, which does exactly that.
> Use `get_flag_names` more consistently

- graphql_api/types/commit/commit.py
- services/components.py
The recent switch to `get_flag_names` has caused a couple of "new" Sentry errors. Though they are not really "new", but rather just different from previous errors.
It seems like the existing code is passing `None` as Report in a bunch of places, and has seemingly always done so. The error now is just a different one.
Nonetheless, I paper over that error in some places by defaulting to `[]` instead on an empty Report. The code will still fail on a different line though.
---
"Fixes" [API-BF1](https://codecov.sentry.io/issues/6387980402), [API-BEZ](https://codecov.sentry.io/issues/6387028994/) and [API-BF2](https://codecov.sentry.io/issues/6387980405/)
> "Fix" errors calling `get_flag_names` on `None`

- graphql_api/dataloader/bundle_analysis.py
- services/bundle_analysis.py
- utils/test_results.py
if we don't pass the repoid, then it won't check the feature flag, and it will be stuck on the old implementation
so it's possible that somewhere else the file is being written using the new implementation, so this will fail to decompress it properly
this is just temporary until we hardcode the new impl to be the default
> fix: pass repoid to get_appropriate_storage_service

- graphql_api/tests/test_commit.py
- graphql_api/types/commit/commit.py
I’m about to remove the additional arguments to `Report.get`, so lets first remove any remaining usage.
> Remove usage of additional `Report.get` arguments

- billing/views.py
Removes the explicit email sent to me for debugging purposes lol. They have been
sending just fine.
> chore: Remove debug email from billing emails logic

- graphql_api/tests/test_test_analytics.py
- graphql_api/types/test_analytics/test_analytics.py
- utils/test_results.py
2 things:
- moving dedup from the test_analytics resolver to get_results
- changing dedup to fill_nan values with 0
> fix: replace NaN values in deduped TA table

- codecov/settings_base.py
- templates/admin/base_site.html
If you use the django admin site while impersonating, it gets ugly (becomes very visually apparent that you are in an altered state)
https://github.com/codecov/engineering-team/issues/3465
preview from my local (the banner got cut off, it says `Impersonating (return to codecov.io and log out)`):
> add impersonation styling to django admin

- upload/tests/views/test_uploads.py
- upload/views/upload_coverage.py
- upload/views/uploads.py
Based on in-person conversation we figured out we were missing metrics from the upload-only endpoint. The metric was only added to the new do it all create-commit create-report create-upload endpoint, but some uploads still go the old ones and we were missing those.
> fix: Capture uploads for upload-only endpoint also

- services/tests/test_report.py
The `build_report_from_commit` fn is calling directly through to the `build_report` fn. Its only purpose is to default the `report_class`.
I would like to remove this indirection, and this test is in the way.
> Remove tests for `build_report`

- graphql_api/tests/test_test_analytics.py
`worker` thinks the default name for our bucket is `archive` but `codecov-api` thinks it's `codecov`. tests hardcode values based on that assumption. if you try to run tests for both repos with a unified config, one repo or the other will fail tests based on which value you chose
API was relatively easy to fix. there's just this one spot where we have to replace a hardcoded value with a setting
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate …
> read test bucket name from config instead of hardcoding

- graphql_api/types/bundle_analysis/base.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
- graphql_api/types/coverage_analytics/coverage_analytics.py
- graphql_api/types/impacted_file/impacted_file.py
- graphql_api/types/pull/pull.py
I was very surprised that a ton of functions that have a trace annotation are not actually creating separate tracing spans.
It is highly probable that the trace annotation interacts with some other graphql or async related annotations in such a way that it does not work properly. Reordering it to be the last (aka inner-most) should hopefully solve this problem.
> Reorder trace annotations

- core/commands/repository/interactors/activate_measurements.py
- core/commands/repository/interactors/tests/test_activate_measurements.py
- timeseries/helpers.py
- timeseries/tests/test_helpers.py
Previously, the "owner measurements" would trigger backfilling of timeseries data for each repo one-by-one, leading to suboptimal N+1 queries.
The logic is now changed to do this as a batch, so we only run a single query to figure out the start/end date of the backfill.
---
Fixes https://github.com/codecov/internal-issues/issues/1222
> Batch triggering timeseries backfills

- Makefile
- pyproject.toml
- uv.lock
see resulting test file paths here: https://app.codecov.io/gh/codecov/codecov-api/tests/matt%2Fmonorepo-friendly-junit
sort by "Last run" to get the results of the most recent attempt
this is a bit of a hack, but better solutions are all way, way easier after cutover and involve more invasive changes to how things work.
the worker/shared/api PRs pass `--rootdir=${PYTEST_ROOTDIR} -c pytest.ini` to pytest invocations. `--rootdir=${PYTEST_ROOTDIR}` allows us to override the rootdir, and `-c pytest.ini` makes sure pytest can still find its config when we do.
by default, the rootdir is `.`, which is the directory `pytest.ini` lives in. it's as if neither argument were passed at all. the original worker/api/shared repos use the default, so they are unchanged.
[the gha-workflows …
> emit junit results in a monorepo-friendly way

- graphs/helpers/badge.py
- graphs/tests/test_helpers.py
Adds a function for creating bundle analysis svg badge from a bundle size in bytes and optionally a level of precision for rounding. They are not yet used anywhere - that will be the next PR.
Closes https://github.com/codecov/engineering-team/issues/3487
> feat: Add bundle badge svgs

- graphs/tests/test_badge_handler.py
- graphs/tests/test_bundle_badge_handler.py
- graphs/urls.py
- graphs/views.py
Adds new graph endpoints for getting new bundle analysis badges.
- Bundle name is required in the url
- Branch name is optional param
- Precision is optional param (one of 0, 1, 2(default))
Example:
[![codecov](https://stage-api.codecov.dev/gh/codecov/gazebo/main/graph/bundle/gazebo-staging-system/badge.svg)](https://stage-web.codecov.dev/gh/codecov/gazebo/bundles/main/gazebo-staging-system)
[![codecov](https://stage-api.codecov.dev/gh/codecov/gazebo/main/graph/bundle/gazebo-staging-system/badge.svg?precision=1)](https://stage-web.codecov.dev/gh/codecov/gazebo/bundles/main/gazebo-staging-system)
[![codecov](https://stage-api.codecov.dev/gh/codecov/gazebo/main/graph/bundle/gazebo-staging-system/badge.svg?precision=0)](https://stage-web.codecov.dev/gh/codecov/gazebo/bundles/main/gazebo-stagi …
> feat: Create API for bundle size badges

- core/commands/repository/interactors/fetch_repository.py
- core/commands/repository/repository.py
- graphql_api/types/coverage_analytics/coverage_analytics.py
- graphql_api/types/owner/owner.py
- graphql_api/types/repository/repository.py
This primarily adds Sentry tags to GraphQL endpoints that resolve any kind of field on `Repository.commit`, etc. This should make it a lot easier to search for traces related to a specific repo or commit.
> Emit owner/repo/commit tags for GraphQL queries

- upload/tests/views/test_bundle_analysis.py
- upload/views/bundle_analysis.py
Will use the "result" label in Grafana to look at error rates. 
> Bundle Analysis: Add metric label for upload result

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.py
We have a graphQL field `isFirstPullRequest` on the Repository object that does an expensive query `count` on pulls table. This is used to evaluate things like
* whether to show a special [banner](https://github.com/codecov/gazebo/blob/819dcd98834f0322caa3bb6a86581bda1d7ebf34/src/pages/RepoPage/CoverageTab/OverviewTab/OverviewTab.tsx#L84C7-L86C16) on Coverage Overview Page
* whether to show a "No data yet" empty state for Test Analytics [page](https://github.com/codecov/gazebo/blob/819dcd98834f0322caa3bb6a86581bda1d7ebf34/src/pages/RepoPage/FailedTestsTab/FailedTestsPage/FailedTestsTable/FailedTestsTable.tsx#L300C2-L316C4)
Update to use a less expensive query (nice idea from @michelletran-codecov )
Closes https://github.com/codecov/engineering-team/issues/3514
> fix: Fix query for is_first_pull_request

- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__analytics_flag_filter__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__analytics_term_filter__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__analytics_testsuite_filter__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_asc__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_asc_first_1__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_asc_first_1_after__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_asc_first_1_after_no_next__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_asc_last_1__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_asc_last_1_before__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_asc_last_1_before_no_previous__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_first_1__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_first_1_after__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_first_1_after_no_next__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_last_1__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_last_1_before__0.json
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__results_pagination_last_1_before_no_previous__0.json
- graphql_api/tests/test_test_analytics.py
- graphql_api/types/test_analytics/test_analytics.py
- utils/test_results.py
> feat: remove test_id from test_results in GQL

- codecov_auth/tests/unit/test_authentication.py
- core/commands/repository/interactors/fetch_repository.py
- core/commands/repository/repository.py
- core/commands/repository/tests/test_repository.py
- graphql_api/helpers/requested_fields.py
- graphql_api/tests/test_requested_fields.py
- graphql_api/types/owner/owner.py
Previously, the `owner.repository` resolver would unconditionally execute a very complicated query through `fetch_repository`.
We can avoid that expensive subquery by inspecting the requested fields as stated in the graphql query.
---
This might fix https://github.com/codecov/engineering-team/issues/3396
> Optimize `fetch_repository` resolver

- graphql_api/actions/repository.py
- graphql_api/types/me/me.py
- graphql_api/types/owner/owner.py
By looking at some random traces, I found that the functions being traced were only *creating* querysets, but they were not the functions that actually *evaluated* those querysets.
> Move trace annotation to correct fn

- upload/helpers.py
- upload/tests/test_helpers.py
I removed a fn which has only directly forwarded calls to the other fn in shared, but renamed one of the kwargs, which I missed.
This now renames the kwarg properly.
---
Fixes a small regression from https://github.com/codecov/codecov-api/pull/1266
Fixes [API-BSR](https://codecov.sentry.io/issues/6504330364/)
> Correct kwarg for `get_github_integration_token`

- graphql_api/dataloader/loader.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
With this change, we now have proper types and thus autocompletion for all the XYZLoader.loader() calls.
> Improve BaseLoader and other type annotations

- graphql_api/actions/commits.py
- graphql_api/types/commit/commit.py
- graphql_api/types/repository/repository.py
This is performing an aggregated group-by query, instead of doing 2N+1 queries resolving all the `commit_status`es for the `repository.commits` as part of the `Commits` GraphQL query.
---
Fixes https://github.com/codecov/engineering-team/issues/3401
> Preload the `{coverage,bundle}Status` for commits

- graphql_api/types/commit/commit.py
This is loading the `parent_commit` using the async batch-loading `CommitLoader`.
This way, we can avoid one of the N+1 queries being executed when executing the `GetCommits` GraphQL query.
However, we are still loading all the BA `CommitReport`s separately within `load_bundle_analysis_comparison`, which is another 2N+1 problem on its own. Will solve that one another time :-)
> Use the `CommitLoader` for `bundleAnalysisCompareWithParent`

- graphql_api/types/commit/commit.py
Previously, the resolver would run a `count` just to know how many uploads there are, in order to return them all. Lets avoid that, and just use a really huge limit instead.
> Avoid a `COUNT` resolving the `Commit.uploads`

- Makefile
needed for https://github.com/codecov/umbrella/pull/30
umbrella wants to shell out to worker/api's `Makefile`s, but it needs to override some make variables when it does. for example, umbrella has to build requirements images differently, so it needs to inject its own `REQUIREMENTS_TAG` variable …
> allow Makefile vars including REQUIREMENTS_TAG to be overridden

- graphql_api/types/impacted_file/impacted_file.py
Should resolve https://codecov.sentry.io/issues/6331041997/?environment=production&project=5514400&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=3 
> Fix: resolve quick bug for results invalid type

- api/shared/compare/serializers.py
- graphql_api/actions/comparison.py
- graphql_api/types/commit/commit.py
- graphql_api/types/comparison/comparison.py
- graphql_api/types/impacted_file/impacted_file.py
- graphql_api/types/pull/pull.py
- pyproject.toml
- services/comparison.py
- upload/serializers.py
- uv.lock
This primarily improves some typings related to `Comparison/Report`, adds some tracing, and removes the need to initialize the related `Repository` when initializing the `ArchiveService` as that is not needed.
> Improve typing and optimize `Comparison`

- graphql_api/types/impacted_file/impacted_file.py
- services/billing.py
- services/tests/test_billing.py
Need to debug: https://codecov.sentry.io/issues/5909837528/?environment=production&project=5215654&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=3 
we're not getting enough logs in prod 
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in …
> chore: More logging to stripe update default method 

- codecov_auth/admin.py
- codecov_auth/tests/test_admin.py
- core/admin.py
This nulls out the `get_deleted_objects`, which is used by the django admin to display a list of objects, and more importantly related objects being deleted.
As in particular with big owners/repos, actually building the list of all the related objects is unreasonably slow, so slow in fact that showing the confirmation dialog times out.
To not block deletes of deeply nested object hierarchies, this will just return empty lists instead.
---
This should fix https://github.com/codecov/internal-issues/issues/1302
> Make delete confirmation more lightweight

- docker-compose.yml
- docker/test.yml
- graphql_api/tests/snapshots/analytics__TestAnalyticsTestCase__gql_query_with_new_ta__0.json
- graphql_api/tests/test_test_analytics.py
- graphql_api/types/test_analytics/test_analytics.py
- rollouts/__init__.py
- utils/test_results.py
i'm introducing 2 things here:
- the ability to read the output of the new ta cache rollups code in
the new location in GCS
- the ability to read multiple versions of the new rollup file
- its probable that the "no version" file never exists in prod GCS
but i'd like to establish this pattern in the code nonetheless
i also add metrics
> feat: add ability to read new file format

- codecov_auth/admin.py
- codecov_auth/tests/test_admin.py
This new action triggers the "sync_repos" for the selected owner from the admin dashboard. Would have been helpful for me today.
(only tested through the unit tests)
> feat(admin): add action to trigger sync repos

- codecov_auth/admin.py
i thought lint was blocking here. oh well
> fix: address lint errors that made it to main
