- codecov_auth/commands/owner/interactors/cancel_trial.py
- codecov_auth/commands/owner/interactors/tests/test_cancel_trial.py
- codecov_auth/commands/owner/owner.py
- codecov_auth/commands/owner/tests/test_owner.py
- graphql_api/tests/mutation/test_cancel_trial.py
- graphql_api/types/inputs/cancel_trial.graphql
- graphql_api/types/mutation/__init__.py
- graphql_api/types/mutation/cancel_trial/__init__.py
- graphql_api/types/mutation/cancel_trial/cancel_trial.graphql
- graphql_api/types/mutation/cancel_trial/cancel_trial.py
- graphql_api/types/mutation/mutation.graphql
- graphql_api/types/mutation/mutation.py
- plan/service.py
We're adding a mutation to cancel a customer's trial should they decide to do so.
This is an add-on ticket to branch `CODE-3605-add-trial-logic` so I left some comments there to adjust that when this is merged in
https://codecovio.atlassian.net/browse/CODE-3644
- Add cancel_trial mutation + gql schema setup
- Adds tests
- Adds `cancel_trial` method in PlanService class
> Code 3644 misc trial additions

- api/internal/self_hosted/serializers.py
- services/self_hosted.py
- validate/views.py
Addresses https://github.com/codecov/codecov-api/security/code-scanning/1 and https://github.com/codecov/codecov-api/security/code-scanning/2
> fix: Ensure we don't accidentally leak stack trace info

- README.md
- Just making a minor change to the markup
N/A
- Just making a minor change to the markup …
> ref: Update word formatting in README

- core/management/commands/backfill_commits.py
- core/tests/test_management_commands.py
To match the config here: https://github.com/codecov/k8s-v2/pull/742
> ref: Update queue name for backfill commits command

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
- Makefile
Make the makefile commands consistent with other apps
> Makefile consistency

- upload/helpers.py
- upload/tests/test_upload.py
Seems there are cases where the pull does not have a `commentid`.  This is causing erroneous notifications that include the "we're processing your commit" message instead of the report info.
N/A
Disables the early notify for now.
> fix: Disable early notify comment

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
> Updating workflows

- docker/Dockerfile.requirements
> Use alpine 3.18

- codecov_auth/views/github.py
> Adding host override for redirect

- .github/workflows/ci.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
> Updating workflows to include setting codecov url

- graphql_api/tests/test_branch.py
- graphql_api/types/commit/commit.py
fixing some conditions for the filters in commit path contents 
> fix: Fix flags filter

- codecov_auth/commands/owner/interactors/save_terms_agreement.py
> Always send to mkto

- upload/helpers.py
- upload/tests/test_upload.py
Reverts codecov/codecov-api#345
> Revert "fix: if upload moves commit to other branch, possibly update branch model head"

- codecov_auth/commands/owner/interactors/get_org_upload_token.py
- codecov_auth/commands/owner/interactors/tests/test_get_org_upload_token.py
> fix: Update org token to check if user is authenticated 

- codecov_auth/commands/owner/interactors/get_org_upload_token.py
- codecov_auth/commands/owner/interactors/tests/test_get_org_upload_token.py
> Update with unauthorized error for org token  

- requirements.in
- requirements.txt
> update shared commit

- Makefile
Uploads test results to codecov
> build: upload test results

- codecov_auth/middleware.py
- codecov_auth/tests/unit/test_middleware.py
> fix: Allow health endpoint access if guest access is set to false

- codecov/settings_base.py
- codecov_auth/middleware.py
- codecov_auth/tests/unit/test_middleware.py
> Revert guest feature

- .github/workflows/ci.yml
Disable to reduce CI error until reprioritized.
> disable ats for now

- .github/workflows/ci.yml
> Test prodvana

- requirements.in
- requirements.txt
bump cryptography version 
https://github.com/codecov/internal-issues/issues/295
> upgrade cryptography

- codecov_auth/tests/unit/views/test_okta.py
- codecov_auth/urls.py
- codecov_auth/views/okta.py
- docker/test.yml
Change okta config to be more consistent with other providers
> Updating okta conf

- .github/workflows/ci.yml
> Fix pvn workflow

- requirements.in
- requirements.txt
bump cryptography and django versions
https://github.com/codecov/internal-issues/issues/295
https://github.com/codecov/internal-issues/issues/234
> upgrades cryptography and django versions (via shared)

- codecov/commands/exceptions.py
- graphql_api/tests/test_owner.py
- graphql_api/types/query/query.py
Reverts codecov/codecov-api#458
> Revert "feat: Guest feature attempt 2"

- validate/views.py
Fixes incorrect import used in https://github.com/codecov/codecov-api/pull/472
> Fix sentry metrics import in validate endpoint

- docker/Dockerfile
- docker/Dockerfile.requirements
Updates berglas and setuptools
> Update berglas version

- api/internal/tests/views/test_user_viewset.py
- requirements.in
- requirements.txt
would add: 
- https://github.com/codecov/shared/pull/183
- https://github.com/codecov/shared/pull/184
- https://github.com/codecov/shared/pull/185
> update to latest shared

- requirements.in
- requirements.txt
> update shared version

- requirements.in
- requirements.txt
Dependency update to fix https://github.com/advisories/GHSA-jjg7-2v4v-x38h
[changelog](https://github.com/kjd/idna/blob/master/HISTORY.rst)
Closes https://github.com/codecov/internal-issues/issues/414
updated dependency to 3.7 from 2.8. Added to requirements.in and ran pip-compile.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …
> chore: bump idna from 2.8 to 3.7

- requirements.in
- requirements.txt
> Update shared latest

- upload/tests/views/test_reports.py
- upload/views/reports.py
> Adding metrics report_results

- requirements.in
- requirements.txt
This update to the shared library will include the changes to update report coverage precision.
ref: https://github.com/codecov/engineering-team/issues/1631
Full list of changes to `shared` in here: https://github.com/codecov/shared/compare/codecov:f6c2c3852530192ab0c6b9fd0c0a800c2cbdb16f%5E%5E%5E%5E%5E...codecov:ae6e12f3cf43188a6d6fa0156ccb78252d3405a8
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, …
> Update shared library to include report models and migrations

- requirements.in
- requirements.txt
Needed for onboarding failed tests.
> Update shared version in api

- .github/workflows/ci.yml
- .github/workflows/mypy.yml
- .github/workflows/self-hosted-release-pr.yml
- .github/workflows/self-hosted-release.yml
fixes https://github.com/codecov/infrastructure-team/issues/385
> chore(ci): bump to 1.2.21 for gha-workflows

- requirements.in
- requirements.txt
> bump shared

- core/signals.py
> sad reacts only

- requirements.in
- requirements.txt
> Debug ReportFileSummary slowness

- services/bundle_analysis.py
> bundle analysis: add in filtering for bundle total size

- api/public/v2/owner/views.py
- api/public/v2/tests/test_api_owner_viewset.py
We have a list endpoint - adding a detail endpoint so you can GET a user by username or ownerid
> add user detail endpoint

- api/public/v2/test_results/serializers.py
- api/public/v2/tests/test_test_results_view.py
Quickly adding name and commits failed to test results endpoint. 
> Update test results endpoint with name and commit ids

- codecov_auth/commands/owner/interactors/trigger_sync.py
- graphql_api/actions/path_contents.py
> chore(lint): trigger_sync annotations

- codecov/settings_base.py
Fixing CSP complaining about worker blob: as it was using default CSP 
> fix CSP for worker src

- codecov/settings_base.py
> Update settings-base CSP

- graphql_api/types/enums/enums.py
The linter is failing on the main build.
> Fix format to appease linter

- requirements.in
- requirements.txt
> Bump shared to latest

- graphql_api/tests/test_repository.py
- graphql_api/types/enums/enums.py
- graphql_api/types/enums/test_results_ordering_parameter.graphql
- reports/tests/factories.py
needed for failed tests. 
ps. i didn't add tests for updated at because it's a pain and it's not worth it.
> feat: Support ordering in test results

- graphql_api/types/owner/owner.graphql
Fixes: https://codecov.sentry.io/share/issue/aed59a66817642b6823cffc3f2fc9486/ …
> fix: Fix isUserOktaAuth so it accepts returned null values

- codecov_auth/admin.py
- codecov_auth/tests/test_admin.py
- requirements.in
- requirements.txt
minor changes to improve use for the Owner Admin
> further OwnerAdmin refinement

- graphql_api/tests/test_repository.py
- graphql_api/types/repository/repository.py
Closes out https://codecov.sentry.io/issues/5669747230/?project=5215654&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=10
> fix: Remove exc_info

- .github/workflows/ci.yml
> Bump to 1.22

- README.md
> testing cd

- codecov/settings_base.py
https://github.com/codecov/engineering-team/issues/2000
> add startup license logging to api

- requirements.in
- requirements.txt
https://github.com/codecov/internal-issues/issues/681
> bump django version

- graphql_api/tests/test_commit.py
- requirements.in
- requirements.txt
Updated assets fetching to have an explicit ordering, fix tests.
> bundle analysis: fix unit test

- codecov_auth/admin.py
- requirements.in
- requirements.txt
New field for True Tokenless 
https://github.com/codecov/engineering-team/issues/2297
> add upload_token_required_for_public_repos

- upload/tests/test_upload.py
Noticed this failing on another PR of mine.
> fix: lint error in test_upload.py

- codecov_auth/templates/admin/custom_page.html
- services/repo_providers.py
Token was not passed into the right functions.
> fix: empty_upload not authenticating correctly

- graphql_api/tests/test_account.py
- graphql_api/types/account/account.graphql
- graphql_api/types/account/account.py
Adds resolver for activatedUserCount on the Account object.
Closes https://github.com/codecov/engineering-team/issues/2557
> feat: Add activatedUserCount resolver to Account

- docker/Dockerfile.requirements
Fixes https://github.com/orgs/codecov/projects/31/views/11?pane=issue&itemId=81251410&issue=codecov%7Cinternal-issues%7C817
Updates to latest version of expat
> [vuln] Update expat

- upload/views/bundle_analysis.py
Was making sure metrics work and it doesn't break the entire thing, it works so gonna remove the try/catch
> bundle analysis: prometheus, remove try/catch

- services/task/task.py
Disables billing emails while we fix some HTML template issues.
> Disable emails

- docker/Dockerfile
> chore(deps): bump berglas to 2.0.6

- codecov_auth/tests/test_admin.py
- plan/service.py
- plan/tests/test_plan.py
Reverts codecov/codecov-api#972
> Revert "Temporarily disable trials starting for paid orgs"

- .github/workflows/ci.yml
This will allow us to download the JUnit XML files that gets generated during the CI run. Having the raw file will be useful for debugging test analytics stuff.
This just updates the workflow. The updated workflow does the upload artifact.
> Update CI to expose JUnit Artifacts

- requirements.in
- requirements.txt
This reverts commit 0bcf77b9db5cb0259ea3106bb2fc7107377ff514.
> Revert "Update `shared` to pull in migrations (#1096)"

- requirements.in
- requirements.txt
Updates shared dep to 5bcbfc8.
> chore: Update shared to 5bcbfc8

- requirements.in
- requirements.txt
Incorrect hash for shared version previously, this used the real hash.
> fix: update shared latest 

- webhook_handlers/views/__init__.py
- webhook_handlers/views/bitbucket.py
- webhook_handlers/views/bitbucket_server.py
- webhook_handlers/views/github.py
- webhook_handlers/views/gitlab.py
> add webhook handler prometheus counters

- graphql_api/types/plan/plan.py
Fixing https://codecov.sentry.io/issues/4659541030/?environment=production&project=5215654&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=7d&stream_index=11
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I …
> fix: Trial status might be an empty string 

- core/commands/commit/interactors/get_file_content.py
This PR updates the logs for the filecontent interactor so we can try and get some better log filtering and understand if there are any systemic issues more clearly
> chore: Update file content log for slightly easier debugging

- requirements.in
- requirements.txt
Updates shared to e6906af1afcb7c32cbdc79c425589b306f4b8c43
> chore: Update shared to e6906af

- requirements.in
- requirements.txt
there's a bug in the previous version of shared that we have rolled back in this version
> deps: update shared

- docker/Dockerfile
Adds collect static back to fix CSS issue on django admin when debug=FALSE
https://stackoverflow.com/questions/4420378/why-does-my-django-admin-site-not-have-styles-css-loading
> fix: Add collectstatic back to dockerfile

- upload/tests/views/test_bundle_analysis.py
- upload/tests/views/test_test_results.py
- upload/tests/views/test_uploads.py
- upload/views/bundle_analysis.py
- upload/views/test_results.py
- upload/views/uploads.py
This reverts commit b43c76552dd118dbd98f43809dc79dc5170df014.
> Revert "feat: Track Upload Sent events for Coverage/BA/TA (#1162)"

- pyproject.toml
- uv.lock
> chore: Update shared to 82e98e5

- pyproject.toml
- uv.lock
This PR bumps shared to latest. Includes the following commits:
https://github.com/codecov/shared/commit/f457962f5e17d70cab40deb12b29116d08c54efd
https://github.com/codecov/shared/commit/617aadb5182455ca416e24ddf07e4a518dc88deb
https://github.com/codecov/shared/commit/a93b0f1299841e56d8ceb591813974e97bec75b9
https://github.com/codecov/shared/commit/87e34049b82aed55d9924af490c9efc27083eed9
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to …
> dev: Bump shared to latest

- graphs/helpers/badge.py
- graphs/tests/test_helpers.py
Creates an 'unknown' bundle size variant of the svg and adds a test for it.
> fix: Tweak bundle badge

- codecov/settings_base.py
followup to https://github.com/codecov/codecov-api/pull/1229
https://github.com/codecov/engineering-team/issues/3465
> magic numbers II

- pyproject.toml
- uv.lock
Update Django version to 4.12.7 
Fixes https://github.com/codecov/internal-issues/issues/1260
> fix: Fix Django vulnerability  

- pyproject.toml
- uv.lock
> chore: Bump shared version
